{
  "hash": "8e6a235d32820ff666b6568dbf2b7854",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Diseño en Bloques Completos al Azar (DBCA)\"\nformat: pdf\n---\n\n![Figura 29. Mapa conceptual (p. 85). Gutiérrez Pulido, H., y De la Vara Salazar, R. (2012). Análisis y diseño de experimentos (3ª ed.). McGraw-Hill/Interamericana de México. ISBN: 9786071507259.](images/4_DBCA/DBCA.PNG)\n\nLa figura 29 presenta los principales componentes de los **diseños en bloques** (Figura 29), una estrategia experimental usada para controlar la variabilidad mediante la formación de grupos homogéneos llamados *bloques*. Entre estos diseños se encuentra el **Diseño en Bloques Completos al Azar (DBCA)**, el cual incorpora el *efecto de bloque* y requiere definir claramente las **hipótesis**, el **modelo estadístico**, así como la **selección y aleatorización** de las unidades experimentales. El análisis estadístico del DBCA se realiza mediante un **ANOVA de dos vías**, el cual permite evaluar simultáneamente el efecto de los tratamientos y de los bloques sobre la variable respuesta.\n\nOtros diseños relacionados incluyen el **diseño en bloques incompletos balanceados** y los diseños **en cuadro latino** y **grecolatino**, los cuales permiten controlar simultáneamente múltiples fuentes de variación. Cada uno de estos diseños exige un procedimiento estructurado que abarca la formulación del modelo, el análisis de varianza correspondiente y la **interpretación** de los resultados.\n\n## Modelo teórico para el Diseño de Bloques Completamente al Azar (DBCA)\n\nEl **Diseño en Bloques Completos al Azar (DBCA)** se utiliza cuando existe una fuente de variación conocida **denominada *bloques*** que puede influir en la variable de respuesta. Para controlar esa variabilidad, las unidades experimentales se agrupan en bloques homogéneos, y dentro de cada bloque los tratamientos se asignan aleatoriamente [@gutierrez2012analisis; @Montgomery2017].\n\nEl modelo lineal aditivo correspondiente al DBCA se expresa como:\n\n$$\nY_{ij} = \\mu + \\tau_i + \\beta_j + \\varepsilon_{ij}\n$$\n\ndonde:\n\n-   $Y_{ij}$: valor observado del tratamiento $i$ en el bloque $j$\n-   $\\mu$: media general\n-   $\\displaystyle \\tau_i$: efecto del tratamiento $i$\n-   $\\displaystyle \\beta_j$: efecto del bloque $j$\n-   $\\displaystyle \\varepsilon_{ij}$: error aleatorio asociado, con $\\displaystyle \\varepsilon_{ij} \\sim N(0,\\sigma^2)$\n\nPara ello se formulan las siguientes hipótesis estadísticas:\n\n$$\nH_0 : \\mu_1 = \\mu_2 = \\cdots = \\mu_k\n$$\n\n$$\nH_A : \\mu_i \\ne \\mu_j \\quad \\text{para algún } i \\ne j\n$$\n\nEstas hipótesis permiten evaluar si existen diferencias significativas entre los tratamientos más allá de la variabilidad explicada por los bloques.\n\n## Análisis de varianza\n\nDe acuerdo con [@gutierrez2012analisis], las hipótesis planteadas en las ecuaciones anteriores se evalúan mediante un análisis de varianza de dos vías, debido a que en el DBCA es necesario considerar simultáneamente dos fuentes de variación: los tratamientos y los bloques. La Tabla presenta el formato general del ANOVA correspondiente a un diseño en bloques completos al azar.\n\n### Tabla ANOVA para un diseño en bloques completos al azar\n\n| Fuente de variabilidad | Suma de cuadrados | Grados de libertad | Cuadrado medio | Estadístico F | Valor-p |\n|------------|------------|------------|------------|------------|------------|\n| Tratamientos | $SC_{TRAT}$ | $k - 1$ | $CM_{TRAT}$ | $F_0 = \\frac{CM_{TRAT}}{CM_E}$ | $P(F > F_0)$ |\n| Bloques | $SC_B$ | $b - 1$ | $CM_B$ | $F_0 = \\frac{CM_{B}}{CM_E}$ | $P(F > F_0)$ |\n| Error | $SC_E$ | $(k - 1)(b - 1)$ | $CM_E$ | --- | --- |\n| Total | $SC_T$ | $kb - 1$ | --- | --- | --- |\n\nNota: SC: Suma de cuadrados; CM: Cuadrado medio; $k$: número de tratamientos; $b$: número de bloques. TRAT: Tratamiento.\n\n## Problema\n\n::: callout-note\nEl crecimiento de las plantas de frijol (*Phaseolus vulgaris*) depende en gran medida de la interacción entre sus raíces y los microorganismos del suelo, especialmente los rizobios, los cuales establecen una relación simbiótica mediante la formación de nódulos radiculares que facilitan la fijación biológica de nitrógeno (FBN). Este proceso constituye una fuente natural y sostenible de nitrógeno, fundamental para el desarrollo y rendimiento del cultivo.\n\nNo obstante, la eficiencia de esta simbiosis puede verse afectada por factores edáficos y ambientales como la composición del suelo, la disponibilidad de humedad, la temperatura y la intensidad lumínica, los cuales generan variabilidad en las condiciones experimentales y pueden influir directamente sobre el crecimiento de las plantas y la actividad microbiana asociada.\n\nDebido a esta variabilidad, resulta apropiado emplear un Diseño en Bloques Completos al Azar (DBCA), donde los bloques permiten controlar parcialmente el efecto de factores ambientales no controlados. En este contexto, se evaluó la respuesta del frijol frente a diferentes tratamientos de fertilización que combinan fuentes químicas y biológicas, incluyendo bioinoculantes y abonos orgánicos, con el propósito de identificar diferencias significativas en el crecimiento del cultivo y promover estrategias de manejo más sostenibles (@fig-DBCA_frijol)\n:::\n\n\n![Plantas de Phaseolus vulgaris utilizadas en el experimento.](images/4_DBCA/DBCA_frijol.png){width=\"326\"}{#fig-DBCA_frijol}\n\nImagen suministrada por el profesor Christian Chacín. Laboratorio de Cultivos Vegetales UDES (2025).\n## Estructura de la base de datos\n\nEl presente experimento se estructuró bajo un **Diseño en Bloques Completos al Azar (DBCA)** con el objetivo de evaluar el efecto de diferentes tratamientos de fertilización sobre el crecimiento de plantas de frijol (*Phaseolus vulgaris*). Este diseño permite controlar parcialmente la variabilidad asociada a factores ambientales no experimentales mediante la conformación de bloques homogéneos.\n\nSe establecieron tres bloques (A, B y C), dentro de los cuales se asignaron aleatoriamente cuatro tratamientos de fertilización:\n\n-   **NPK comercial;**\n\n-   **NPK + bioinoculante;**\n\n-   **Orgánico + NPK (50:50);**\n\n-   **Orgánico + NPK.**\n\nCada tratamiento fue evaluado mediante diez observaciones dentro de cada bloque, generando un diseño balanceado con un total de 120 unidades experimentales.\n\nLa variable respuesta, denominada `Resultado`, corresponde a una variable cuantitativa continua asociada al crecimiento vegetal, expresada en valores decimales.\n\n## Unidad experimental\n\n> Cada planta de *Phaseolus vulgaris* evaluada dentro de cada combinación tratamiento × bloque constituyó una unidad experimental independiente.\n\n## Definición de bloques\n\n> Los bloques correspondieron a diferentes sectores del área experimental con condiciones ambientales relativamente homogéneas, utilizados para controlar parcialmente la variabilidad asociada a factores externos como humedad, iluminación o características del suelo.\n\n## Descripción de las variables del experimento\n\nEl diseño experimental corresponde a un Diseño en Bloques Completos al Azar (DBCA), en el cual se evaluaron diferentes tratamientos de fertilización en plantas de frijol (*Phaseolus vulgaris*). Los bloques representan grupos homogéneos de unidades experimentales, mientras que la variable respuesta cuantifica el efecto de los tratamientos sobre el crecimiento vegetal.\n\n|   | Tipo de variable | Descripción |\n|:-----------------------|:-----------------------|:-----------------------|\n| **Tratamiento** | Cualitativa nominal | Incluye los diferentes tratamientos de fertilización evaluados: NPK comercial, NPK + bioinoculante, Orgánico + NPK (50:50) y fertilización orgánica. |\n| **Bloque** | Cualitativa nominal | Factor de bloqueo que agrupa las unidades experimentales bajo condiciones similares. Los bloques se identifican como A, B y C. |\n| **Resultado** | Cuantitativa continua | Variable respuesta asociada al crecimiento de las plantas, expresada en valores decimales (por ejemplo, altura de planta en cm). |\n\n## Instalar Paquetes (solo una vez)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"readxl\")\n#install.packages(\"car\") \n#install.packages(\"agricolae\") \n#install.packages(\"lmtest\") \n#install.packages(\"ggplot2\")\n#install.packages(\"gtable\")\n```\n:::\n\n\n## Cargar las librerias necesarias para el análisis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\nlibrary(readxl) \nlibrary(car) \nlibrary(agricolae)\nlibrary(lmtest) \nlibrary(ggplot2)\n})\n```\n:::\n\n\n## Importar datos desde Excel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nDBCA <- read_excel(\"C:/R-Proyectos/r-para-mi/data/DBCA_Frijol/DBCA_frijol.xlsx\")\n\nDBCA$Tratamiento[DBCA$Tratamiento == \"Organico + NPK (50:50)\"] <- \n\"Orgánico + NPK (50:50)\"\n```\n:::\n\n\n## Exploración inicial y estructura de la base de datos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(DBCA)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Tratamiento\" \"Bloque\"      \"Resultado\"  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [120 × 3] (S3: tbl_df/tbl/data.frame)\n $ Tratamiento: chr [1:120] \"NPK Comercial\" \"NPK Comercial\" \"NPK Comercial\" \"NPK Comercial\" ...\n $ Bloque     : chr [1:120] \"A\" \"A\" \"A\" \"A\" ...\n $ Resultado  : num [1:120] 51.5 49.6 51.9 54.6 49.3 ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(DBCA$Resultado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  44.71   52.30   56.76   57.26   61.24   72.39 \n```\n\n\n:::\n:::\n\n\n## Convertir variables a factores\n\nPara garantizar un análisis adecuado bajo un **Diseño en Bloques Completos al Azar (DBCA)**, las variables `Tratamiento` y `Bloque` deben definirse como factores en R. Esta conversión permite que el modelo estadístico reconozca ambas variables como factores categóricos asociados a los efectos experimentales del estudio, evitando que sean interpretadas como variables numéricas continuas.\n\nLa variable `Resultado`, por su parte, se mantiene como una variable cuantitativa continua.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDBCA$Tratamiento <- as.factor(DBCA$Tratamiento)\nDBCA$Bloque      <- as.factor(DBCA$Bloque)\nDBCA$Resultado   <- as.numeric(DBCA$Resultado)\n```\n:::\n\n\n## Modelo lineal para DBCA\n\nCon el fin de evaluar simultáneamente el efecto de los tratamientos de fertilización y de los bloques experimentales sobre la variable respuesta, se ajustó un modelo lineal correspondiente al Diseño en Bloques Completos al Azar (DBCA). Este modelo incorpora tanto el efecto de los tratamientos como la variabilidad asociada a los bloques, permitiendo controlar parcialmente las diferencias ambientales presentes en el experimento.\n\nEl modelo se ajustó en R mediante el siguiente código:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodeloDBCA <- aov(Resultado ~ Tratamiento + Bloque,\n                  data = DBCA)\n\nsummary(modeloDBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nTratamiento   3   3602  1200.6 153.749 <2e-16 ***\nBloque        2     11     5.4   0.688  0.505    \nResiduals   114    890     7.8                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Interpretación\n\nEl análisis del modelo lineal evidenció que el factor `Tratamiento` presentó un efecto altamente significativo sobre la variable respuesta ($F = 153.749$; $p < 2 \\times 10^{-16}$), indicando que existen diferencias estadísticas entre las medias de los tratamientos evaluados.\n\nPor otro lado, el factor `Bloque` no mostró un efecto significativo ($F = 0.688$; $p = 0.505$), lo que sugiere que la variabilidad entre bloques fue baja y no contribuyó significativamente a explicar la variación observada en el experimento.\n\nEn conjunto, los resultados indican que las diferencias detectadas en la altura de las plantas se deben principalmente al efecto de los tratamientos de fertilización y no a variaciones asociadas a los bloques experimentales.\n\n## ANOVA para Diseño de Bloques Completos al Azar -DBCA-\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodeloDBCA <- aov(Resultado ~ Tratamiento + Bloque, data = DBCA)\nsummary(modeloDBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nTratamiento   3   3602  1200.6 153.749 <2e-16 ***\nBloque        2     11     5.4   0.688  0.505    \nResiduals   114    890     7.8                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**Interpretación:** Los resultados del análisis de varianza (ANOVA) correspondientes al Diseño en Bloques Completos al Azar (DBCA) evidenciaron un efecto altamente significativo del factor `Tratamiento` sobre la variable respuesta `Resultado`, mientras que el factor `Bloque` no presentó un efecto estadísticamente significativo.\n\n1\\. **Efecto del Tratamiento**.\n\nEl análisis indica que el factor Tratamiento es altamente significativo sobre la variable de Resultado. Dado que el valor $\\text{p}$ es extremadamente pequeño (denotado por '\\*\\*\\*'), se **rechaza la hipótesis nula** de que no hay diferencias entre las medias de los tratamientos. Esto significa que existe una **diferencia estadísticamente significativa** en el Resultado al menos entre dos de los niveles de Tratamiento. **Grados de Libertad (Df):** 3. **Valor F (F value):** 153.749. **Valor p (**$\\text{Pr}(>F)$): $<2 \\text{e}-16$ (Menor que $0.001$)\n\nEl factor `Tratamiento` mostró diferencias altamente significativas entre sus media ($F=153.749$, $p < 2 \\times 10^{-16}$. En consecuencia, se rechaza la hipótesis nula de igualdad de medias entre tratamientos, indicando que al menos uno de los tratamientos de fertilización produjo un efecto diferente sobre el crecimiento de las plantas de frijol.\n\nEstos resultados sugieren que el tipo de fertilización influye significativamente sobre la variable respuesta evaluada.\n\n-   Grados de libertad: $Df=3$\n\n-   Cuadrado medio: $CM_{TRAT} = 1200.6$\n\n-   Estadístico F: $F = 153.749$\n\n-   Valor de p: $p < 2 \\times 10^{-16}$\n\n2\\. **Efecto del Bloque.**\n\nEl factor `Bloque` no presentó diferencias estadísticamente significativas ($F = 0.688$; $p = 0.505$). Esto indica que la variabilidad asociada a los bloques no fue suficientemente grande para afectar significativamente la variable respuesta.\n\nAunque el bloqueo fue incorporado para controlar posibles fuentes de variación ambiental, los resultados sugieren que las condiciones entre bloques fueron relativamente homogéneas o que el efecto de los tratamientos fue considerablemente mayor que la variabilidad atribuida al bloqueo.\n\n-   Grados de libertad: $Df = 2$\n\n<!-- -->\n\n-   Cuadrado medio: $CM_B = 5.4$\n\n<!-- -->\n\n-   Estadístico F: $F = 0.688$\n\n<!-- -->\n\n-   Valor de p: $p = 0.505$\n\n3\\. **Resumen del Modelo.**\n\nEl análisis evidenció que el factor `Tratamiento` ejerce una influencia significativa sobre la variable respuesta, mientras que el factor `Bloque` no contribuyó significativamente a explicar la variabilidad observada en los datos.\n\nDado que el efecto de tratamientos resultó significativo, es necesario realizar pruebas de comparaciones múltiples *a posteriori* (por ejemplo, Tukey, LSD o Scheffé) con el fin de identificar específicamente cuáles tratamientos difieren entre sí.\n\n## Verificación de supuestos\n\nPara garantizar la validez de los resultados del análisis de varianza (ANOVA), es necesario verificar el cumplimiento de los supuestos estadísticos asociados al modelo. El incumplimiento de estos supuestos puede afectar la confiabilidad de las inferencias obtenidas.\n\nLos principales supuestos evaluados fueron:\n\n-   **Normalidad de los residuos:** establece que los residuos del modelo deben aproximarse a una distribución normal. Este supuesto se evaluó mediante la prueba de Shapiro-Wilk y gráficos diagnósticos.\n\n-   **Homogeneidad de varianzas (homocedasticidad):** supone que la variabilidad de la variable respuesta es similar entre los tratamientos y bloques evaluados.\n\n-   **Independencia de las observaciones:** implica que los errores experimentales sean independientes entre sí, sin autocorrelación entre las observaciones.\n\n### Normalidad de residuos (Shapiro-Wilk)\n\nLa normalidad de los residuos del modelo se evaluó mediante la prueba de Shapiro-Wilk, la cual contrasta la hipótesis nula de que los residuos provienen de una distribución normal. Valores de $p = 0.505$ indican que no existen evidencias suficientes para rechazar dicho supuesto.\n\nEl análisis se realizó mediante el siguiente script en R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- residuals(modeloDBCA)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  res\nW = 0.99559, p-value = 0.9725\n```\n\n\n:::\n:::\n\n\n**Interpretación:** La prueba de Shapiro-Wilk aplicada a los residuos del modelo arrojó un estadístico $W = 0.995$ y un valor de $p = 0.9725$, superior al nivel de significancia de 0.05. Por lo tanto, no existen evidencias estadísticas para rechazar la hipótesis nula de normalidad, indicando que los residuos del modelo presentan una distribución aproximadamente normal. En consecuencia, se considera cumplido el supuesto de normalidad requerido para el análisis de varianza (ANOVA).\n\n**Gráfico Q-Q de los residuos estandarizados**\n\nComo complemento a la prueba de Shapiro-Wilk, se elaboró un gráfico Q-Q (*Quantile-Quantile*) de los residuos estandarizados del modelo. Este gráfico permite evaluar visualmente el supuesto de normalidad mediante la comparación entre los cuantiles observados de los residuos y los cuantiles teóricos de una distribución normal.\n\nCuando los puntos se distribuyen aproximadamente sobre la línea diagonal de referencia, se considera que los residuos presentan un comportamiento compatible con la normalidad.\n\nEl análisis se realizó mediante el siguiente script en R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(res)\nqqline(res, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-docx/unnamed-chunk-13-1.png)\n:::\n\n```{.r .cell-code}\nhist(res, main = \"Histograma de residuos\", xlab = \"Residuos\")\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-docx/unnamed-chunk-13-2.png)\n:::\n:::\n\n\n### Interpretación\n\nEl gráfico Q-Q mostró que los residuos estandarizados se distribuyen cercanos a la línea diagonal de referencia, sin evidenciar desviaciones importantes o patrones sistemáticos. Esto sugiere que los residuos presentan una distribución aproximadamente normal, respaldando visualmente el cumplimiento del supuesto de normalidad requerido para el análisis de varianza (ANOVA).\n\n### Homocedasticidad\n\nLa homogeneidad de varianzas entre tratamientos constituye uno de los supuestos fundamentales del análisis de varianza (ANOVA). Para evaluar este supuesto se aplicaron las pruebas de Bartlett, Levene y Fligner-Killeen, las cuales permiten determinar si la variabilidad de la variable respuesta es similar entre los grupos evaluados.\n\nEl análisis se realizó mediante el siguiente script en R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(Resultado ~ Tratamiento, data = DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  Resultado by Tratamiento\nBartlett's K-squared = 7.4355, df = 3, p-value = 0.05924\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::leveneTest(Resultado ~ Tratamiento, data = DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   3  1.3691 0.2557\n      116               \n```\n\n\n:::\n\n```{.r .cell-code}\nfligner.test(Resultado ~ Tratamiento, data = DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFligner-Killeen test of homogeneity of variances\n\ndata:  Resultado by Tratamiento\nFligner-Killeen:med chi-squared = 3.3125, df = 3, p-value = 0.3459\n```\n\n\n:::\n:::\n\n\n**Interpretación:**\n\nLas pruebas de Bartlett, Levene y Fligner-Killeen presentaron valores de ppp superiores al nivel de significancia de 0.05, indicando que no existen evidencias estadísticas suficientes para rechazar la hipótesis nula de igualdad de varianzas entre tratamientos.\n\nAunque el valor obtenido en la prueba de Bartlett ($p = 0.059$) se encuentra cercano al umbral de significancia, los resultados en conjunto sugieren que el supuesto de homocedasticidad se cumple razonablemente para el modelo analizado, permitiendo continuar con la interpretación del ANOVA y las pruebas de comparación múltiple.\n\n### Gráfico de Residuos vs. Valores Ajustados\n\nComo complemento a las pruebas formales de homogeneidad de varianzas, se construyó un gráfico de residuos estandarizados frente a los valores ajustados del modelo. Este gráfico permite evaluar visualmente la presencia de patrones sistemáticos, cambios en la dispersión o posibles problemas de heterocedasticidad.\n\nCuando los residuos se distribuyen aleatoriamente alrededor de la línea horizontal en cero, sin formar estructuras definidas o patrones tipo cono, se considera que el supuesto de homogeneidad de varianzas se cumple adecuadamente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Extraer valores ajustados y residuos del modelo DBCA\ndatos_homocedasticidad <- data.frame(\n  Valores_Ajustados = fitted(modeloDBCA),     # valores predichos del modelo\n  Residuos_Std = rstandard(modeloDBCA)        # residuos estandarizados\n)\n\n# 2. Gráfico de residuos vs valores ajustados\nggplot(datos_homocedasticidad, aes(x = Valores_Ajustados, y = Residuos_Std)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  theme_minimal() +\n  labs(\n    title = \"Gráfico de Residuos vs. Valores Ajustados (Homogeneidad de Varianzas)\",\n    x = \"Valores ajustados (predichos)\",\n    y = \"Residuos estandarizados\"\n  )\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-docx/unnamed-chunk-15-1.png)\n:::\n\n```{.r .cell-code}\n# Interpretación:\n# Los puntos deben dispersarse aleatoriamente alrededor de y = 0\n# sin formar patrones o conos, indicando homogeneidad de varianzas.\n```\n:::\n\n\n**Interpretación:**\n\nLas pruebas de Bartlett, Levene y Fligner-Killeen, junto con el análisis gráfico de residuos, evidenciaron que el modelo cumple razonablemente el supuesto de homogeneidad de varianzas. El gráfico mostró una dispersión aleatoria de los residuos alrededor de la línea horizontal en cero, sin patrones sistemáticos ni cambios importantes en la variabilidad.\n\nEn consecuencia, se considera válido el uso del análisis de varianza (ANOVA) bajo el Diseño en Bloques Completos al Azar (DBCA), dado que no se detectaron violaciones importantes del supuesto de homocedasticidad.\n\n### Independencia de residuos\n\nLa independencia de los residuos constituye otro de los supuestos fundamentales del análisis de varianza (ANOVA). Este supuesto establece que los errores experimentales deben ser independientes entre sí, es decir, que el valor de un residuo no debe influir sobre otro.\n\nPara evaluar este supuesto se aplicó la prueba de Durbin-Watson, la cual permite detectar la presencia de autocorrelación entre los residuos del modelo.\n\nLas hipótesis evaluadas fueron:\n\n-   **Hipótesis nula (H₀):** los residuos son independientes;\n\n-   **Hipótesis alternativa (H₁):** los residuos presentan autocorrelación.\n\nValores de **p-value \\> 0.05**, indican que no existen evidencias suficientes para rechazar la hipótesis nula de independencia.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndwtest(modeloDBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tDurbin-Watson test\n\ndata:  modeloDBCA\nDW = 2.042, p-value = 0.4159\nalternative hypothesis: true autocorrelation is greater than 0\n```\n\n\n:::\n:::\n\n\n**Interpretación:**\n\nLa prueba de Durbin-Watson arrojó un valor de $DW = 2.042$ y un valor de $p = 0.4159$, superior al nivel de significancia de 0.05. En consecuencia, no existen evidencias estadísticas suficientes para rechazar la hipótesis nula de independencia de los residuos.\n\nAdicionalmente, la cercanía del estadístico $DW$ al valor teórico de 2.042 respalda la ausencia de autocorrelación entre los errores experimentales. Por lo tanto, se considera cumplido el supuesto de independencia requerido para la validez del análisis de varianza bajo el Diseño en Bloques Completos al Azar (DBCA).\n\n## **Pruebas aposteriori**\n\nUna vez verificados los supuestos de normalidad, homogeneidad de varianzas e independencia de los residuos, se realizaron pruebas de comparaciones múltiples *a posteriori* con el propósito de identificar cuáles tratamientos presentan diferencias estadísticamente significativas sobre la variable respuesta evaluada.\n\nEn el contexto del Diseño en Bloques Completos al Azar (DBCA), estas pruebas permiten comparar las medias ajustadas de los tratamientos considerando el efecto de bloqueo incorporado en el modelo experimental. Entre las pruebas más utilizadas se encuentran Tukey, LSD y Scheffé, las cuales permiten identificar diferencias específicas entre pares de tratamientos.\n\nEl uso del DBCA contribuye a reducir la variabilidad experimental asociada a factores externos mediante la conformación de bloques homogéneos, incrementando así la precisión y confiabilidad de las comparaciones estadísticas. En consecuencia, las diferencias detectadas entre tratamientos reflejan principalmente los efectos reales de las condiciones de fertilización evaluadas y no variaciones atribuibles al azar o a fuentes de variación no controladas.\n\n### Tukey HSD (agrupamiento con letras)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHSD.test(modeloDBCA, \"Tratamiento\", group = TRUE, console = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStudy: modeloDBCA ~ \"Tratamiento\"\n\nHSD Test for Resultado \n\nMean Square Error:  7.808829 \n\nTratamiento,  means\n\n                       Resultado      std  r        se   Min   Max     Q25\nNPK + Bioinoculante     54.25933 2.395591 30 0.5101904 49.26 58.09 52.9100\nNPK Comercial           50.29667 2.453096 30 0.5101904 44.71 54.74 48.5975\nOrgánico + NPK          64.78000 3.621806 30 0.5101904 57.14 72.39 62.1700\nOrgánico + NPK (50:50)  59.71300 2.488591 30 0.5101904 55.73 65.66 58.2425\n                          Q50     Q75\nNPK + Bioinoculante    54.045 55.9275\nNPK Comercial          50.080 51.8625\nOrgánico + NPK         65.070 66.9650\nOrgánico + NPK (50:50) 59.480 61.0025\n\nAlpha: 0.05 ; DF Error: 114 \nCritical Value of Studentized Range: 3.687325 \n\nMinimun Significant Difference: 1.881238 \n\nTreatments with the same letter are not significantly different.\n\n                       Resultado groups\nOrgánico + NPK          64.78000      a\nOrgánico + NPK (50:50)  59.71300      b\nNPK + Bioinoculante     54.25933      c\nNPK Comercial           50.29667      d\n```\n\n\n:::\n:::\n\n\n**Interpretación:**\n\nLa prueba de Tukey HSD aplicada al Diseño en Bloques Completos al Azar (DBCA) evidenció diferencias estadísticamente significativas entre todos los tratamientos evaluados sobre la altura de las plantas de frijol. El Tratamiento 4 presentó la mayor media (64.78 cm; grupo a), seguido del Tratamiento 3 (59.71 cm; grupo b), el Tratamiento 2 (54.26 cm; grupo c) y el Tratamiento 1 (50.29 cm; grupo d), el cual registró la menor media.\n\nLa diferencia mínima significativa obtenida mediante la prueba de Tukey fue de 1.88, superior a la observada en la prueba LSD (1.43), lo que refleja el carácter más conservador del método Tukey para el control del error por comparaciones múltiples. A pesar de ello, los tratamientos mantuvieron una separación completa, sin letras compartidas entre grupos, indicando que todas las medias difieren significativamente entre sí al nivel de confianza del 95 %.\n\nEstos resultados confirman que los tratamientos ejercieron efectos claramente diferenciados sobre la altura de las plantas y respaldan la consistencia y confiabilidad de los resultados obtenidos en el experimento.\n\n### Comparaciones múltiples con LSD\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout_LSD <- LSD.test(modeloDBCA, \"Tratamiento\", group = TRUE, console = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStudy: modeloDBCA ~ \"Tratamiento\"\n\nLSD t Test for Resultado \n\nMean Square Error:  7.808829 \n\nTratamiento,  means and individual ( 95 %) CI\n\n                       Resultado      std  r        se      LCL      UCL   Min\nNPK + Bioinoculante     54.25933 2.395591 30 0.5101904 53.24865 55.27002 49.26\nNPK Comercial           50.29667 2.453096 30 0.5101904 49.28598 51.30735 44.71\nOrgánico + NPK          64.78000 3.621806 30 0.5101904 63.76932 65.79068 57.14\nOrgánico + NPK (50:50)  59.71300 2.488591 30 0.5101904 58.70232 60.72368 55.73\n                         Max     Q25    Q50     Q75\nNPK + Bioinoculante    58.09 52.9100 54.045 55.9275\nNPK Comercial          54.74 48.5975 50.080 51.8625\nOrgánico + NPK         72.39 62.1700 65.070 66.9650\nOrgánico + NPK (50:50) 65.66 58.2425 59.480 61.0025\n\nAlpha: 0.05 ; DF Error: 114\nCritical Value of t: 1.980992 \n\nleast Significant Difference: 1.429322 \n\nTreatments with the same letter are not significantly different.\n\n                       Resultado groups\nOrgánico + NPK          64.78000      a\nOrgánico + NPK (50:50)  59.71300      b\nNPK + Bioinoculante     54.25933      c\nNPK Comercial           50.29667      d\n```\n\n\n:::\n:::\n\n\n**Interpretación:**\n\nLa prueba LSD (*Least Significant Difference*) aplicada al Diseño en Bloques Completos al Azar (DBCA) evidenció diferencias estadísticamente significativas entre las medias de altura de las plantas de frijol para todos los tratamientos evaluados. El Tratamiento 4 presentó la mayor altura promedio (64.78 cm; grupo a), seguido del Tratamiento 3 (59.71 cm; grupo b), el Tratamiento 2 (54.26 cm; grupo c) y finalmente el Tratamiento 1 (50.29 cm; grupo d), el cual registró la menor media.\n\nLa diferencia mínima significativa obtenida mediante la prueba LSD fue de 1.43, indicando que diferencias superiores a este valor se consideran estadísticamente significativas al nivel de confianza del 95 %. La ausencia de letras compartidas entre tratamientos confirma que todas las medias difieren significativamente entre sí.\n\nEstos resultados indican que los tratamientos ejercieron efectos diferenciados sobre la altura de las plantas de frijol, más allá de la variabilidad experimental controlada mediante los bloques del diseño.\n\n### Visualización de resultados\n\n### Caja y Bigote (Boxplot en ggplot2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(DBCA, aes(x = Tratamiento, y = Resultado, fill = Tratamiento)) + geom_boxplot() + theme_minimal() + labs( title = \"Distribución del resultado por tratamiento\", x = \"Tratamiento\", y = \"Resultado\")\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-docx/unnamed-chunk-19-1.png)\n:::\n:::\n\n\n**Interpretación:**\n\nLa gráfica de cajas y bigotes muestra la distribución de las alturas de las plantas de *Phaseolus vulgaris* bajo los diferentes tratamientos de fertilización evaluados mediante un Diseño en Bloques Completos al Azar (DBCA). Se observa una tendencia creciente en las medianas de los tratamientos, evidenciando un efecto progresivamente favorable sobre el crecimiento vegetal desde NPK Comercial hasta Orgánico + NPK.\n\nEl tratamiento Orgánico + NPK presentó las mayores alturas promedio, seguido de Orgánico + NPK (50:50), NPK + Bioinoculante y finalmente NPK Comercial, el cual registró los valores más bajos. La dispersión de los datos dentro de cada tratamiento fue relativamente homogénea, aunque se identificó un valor atípico en el tratamiento Orgánico + NPK (50:50), comportamiento frecuente en experimentos biológicos debido a la variabilidad natural entre individuos.\n\nEstos resultados son consistentes con las pruebas de comparación múltiple (LSD y Tukey), las cuales evidenciaron diferencias estadísticamente significativas entre todos los tratamientos evaluados.\n",
    "supporting": [
      "Chapter_05_files\\figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}