{
  "hash": "a814bafb3c68a7749b5a1f89914427ab",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Capítulo 5.Diseño de Bloques Completamente al Azar (DBCA)\"\n---\n\n![Nota. Mapa conceptual (p. 85). Gutiérrez Pulido, H., y De la Vara Salazar, R. (2012). Análisis y diseño de experimentos (3ª ed.). McGraw-Hill/Interamericana de México. ISBN: 9786071507259.](images/4_DBCA/DBCA.PNG)\n\nEl mapa conceptual presenta los principales componentes de los **diseños en bloques**, una estrategia experimental usada para controlar la variabilidad mediante la formación de grupos homogéneos llamados *bloques*. Entre estos diseños se encuentra el **Diseño en Bloques Completos al Azar (DBCA)**, el cual incorpora el *efecto de bloque* y requiere definir claramente las **hipótesis**, el **modelo estadístico**, así como la **selección y aleatorización** de las unidades experimentales. Su análisis se realiza a través del **ANOVA**, que permite evaluar si los tratamientos difieren más allá de la variación entre bloques.\n\nOtros diseños relacionados incluyen el **diseño en bloques incompletos balanceados** y los diseños **en cuadro latino** y **grecolatino**, los cuales permiten controlar simultáneamente múltiples fuentes de variación. Cada uno de estos diseños exige un procedimiento estructurado que abarca la formulación del modelo, el análisis de varianza correspondiente y la **interpretación** de los resultados.\n\n## Modelo teórico para el Diseño de Bloques Completamente al Azar (DBCA)\n\nEl **Diseño en Bloques Completos al Azar (DBCA)** se utiliza cuando existe una fuente de variación conocida ---denominada *bloques*--- que puede influir en la variable de respuesta. Para controlar esa variabilidad, las unidades experimentales se agrupan en bloques homogéneos, y dentro de cada bloque los tratamientos se asignan aleatoriamente.\n\nEl modelo lineal aditivo correspondiente al DBCA se expresa como:\n\n$$\nY_{ij} = \\mu + \\tau_i + \\beta_j + \\varepsilon_{ij}\n$$\n\ndonde:\n\n-   $Y_{ij}$: valor observado del tratamiento $i$ en el bloque $j$\n-   $\\mu$: media general\n-   $\\displaystyle \\tau_i$: efecto del tratamiento $i$\n-   $\\displaystyle \\beta_j$: efecto del bloque $j$\n-   $\\displaystyle \\varepsilon_{ij}$: error aleatorio asociado, con $\\displaystyle \\varepsilon_{ij} \\sim N(0,\\sigma^2)$\n\nPara ello se formulan las siguientes hipótesis estadísticas:\n\n$$\nH_0 : \\mu_1 = \\mu_2 = \\cdots = \\mu_k\n$$\n\n$$\nH_A : \\mu_i \\ne \\mu_j \\quad \\text{para algún } i \\ne j\n$$\n\nEstas hipótesis permiten evaluar si existen diferencias significativas entre los tratamientos más allá de la variabilidad explicada por los bloques.\n\n## Análisis de varianza\n\nDe acuerdo con [@gutierrez2012analisis], las hipótesis planteadas en las ecuaciones anteriores se evalúan mediante un análisis de varianza de dos vías, debido a que en el DBCA es necesario considerar simultáneamente dos fuentes de variación: los tratamientos y los bloques. La Tabla presenta el formato general del ANOVA correspondiente a un diseño en bloques completos al azar.\n\n### Tabla ANOVA para un diseño en bloques completos al azar\n\n| Fuente de variabilidad | Suma de cuadrados | Grados de libertad | Cuadrado medio | Estadístico F                  | Valor-p      |\n|------------|------------|------------|------------|------------|------------|\n| Tratamientos           | SCTRAT            | $k - 1$            | CMTRAT         | $F_0 = \\frac{CM_{TRAT}}{CM_E}$ | $P(F > F_0)$ |\n| Bloques                | SCB               | $b - 1$            | CMB            | $F_0 = \\frac{CM_{B}}{CM_E}$    | $P(F > F_0)$ |\n| Error                  | SCE               | $(k - 1)(b - 1)$   | CME            | ---                            | ---          |\n| Total                  | SCT               | $kb - 1$           | ---            | ---                            | ---          |\n\nNota: SC: Suma de cuadrados, CM: Cuadrado medio.\n\n## Problema\n\n::: callout-note\nEl **crecimiento de las plantas de frijol (*Phaseolus vulgaris*)** depende en gran medida de la interacción entre sus raíces y los **microorganismos del suelo**, especialmente los **rizobios**, los cuales establecen una relación simbiótica formando **nódulos radiculares** que facilitan la **fijación biológica de nitrógeno (FBN)**. Este proceso aporta una fuente natural y sostenible de nitrógeno, fundamental para el desarrollo y rendimiento de las plantas.\n\nSin embargo, el aprovechamiento de esta simbiosis puede verse afectado por **factores edáficos y ambientales** como la **composición del suelo, la disponibilidad de humedad, la temperatura y la luz**, que influyen directamente en la actividad microbiana y en la eficiencia de la FBN.\n\nPor ello, resulta necesario **evaluar la respuesta del frijol frente a diferentes tratamientos de fertilización**, combinando **fuentes químicas y biológicas (bioinoculantes y abonos orgánicos)**, con el fin de identificar estrategias que promuevan un crecimiento óptimo y un manejo más sostenible del cultivo.\n\n![Phaseolus vulgaris](images/4_DBCA/DBCA_frijol.png){width=\"326\"}\n\nImagen suminitrada por el profesor Christian Chacín. Laboratorio de Cultivos Vegetales UDES (2025).\n:::\n\n## Estructura de la base de datos\n\nEl presente experimento se estructuró bajo un **Diseño de Bloques Completamente al Azar (DBCA)** con el objetivo de evaluar el efecto de diferentes tratamientos de fertilización sobre el crecimiento de las plantas de frijol (*Phaseolus vulgaris*). Este diseño permite controlar la variabilidad asociada a factores ambientales no experimentales mediante la conformación de bloques homogéneos.\\\nEn este caso, se consideraron **tres bloques (A, B y C)** que representan unidades experimentales con condiciones similares dentro de cada uno, y se aplicaron **cuatro tratamientos** de fertilización: **NPK Comercial**, **NPK + Bioinoculante**, **Orgánico + NPK (50:50)** y **Orgánico + NPK**.\\\nEl parámetro evaluado, denominado **Resultado**, corresponde a una variable cuantitativa continua (por ejemplo, biomasa, concentración de metal o altura), expresada en valores decimales.\n\n### Descripción de las variables del experimento\n\nEl diseño experimental corresponde a un **Diseño de Bloques Completamente al Azar (DBCA)**, en el cual se evaluaron diferentes tratamientos de fertilización en plantas de frijol (*Phaseolus vulgaris*).\\\nLos bloques representan unidades experimentales homogéneas, y la variable de respuesta cuantifica el efecto del tratamiento sobre el crecimiento o bioacumulación.\n\n|                 | Tipo de variable      | Descripción                                                                                                                                              |\n|:------------------|:------------------|:---------------------------------|\n| **Tratamiento** | Cualitativa nominal   | Incluye los diferentes niveles de fertilización, como *NPK Comercial*, *NPK + Bioinoculante*, *Orgánico + NPK (50:50)*, entre otros.                     |\n| **Bloque**      | Cualitativa nominal   | Factor de bloqueo que agrupa las unidades experimentales bajo condiciones similares. Se identifican con letras (A, B, C, ...).                           |\n| **Resultado**   | Cuantitativa continua | Variable de respuesta que representa la medición obtenida (por ejemplo: altura, biomasa, concentración de metal, etc.), expresada con valores decimales. |\n\n### Instalar Paquetes (solo una vez)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"readxl\")\n#install.packages(\"car\") \n#install.packages(\"agricolae\") \n#install.packages(\"lmtest\") \n#install.packages(\"ggplot2\")\n#install.packages(\"gtable\")\n```\n:::\n\n\n### Cargar las librerias necesarias para el análisis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\nlibrary(readxl) \nlibrary(car) \nlibrary(agricolae)\nlibrary(lmtest) \nlibrary(ggplot2)\n})\n```\n:::\n\n\n### Importar datos desde Excel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nDBCA <- read_excel(\"C:/R-Proyectos/r-para-mi/data/DBCA_Frijol/DBCA_frijol.xlsx\")\n```\n:::\n\n\n### Exploración inicial y estructura de la base de datos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(DBCA)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Tratamiento\" \"Bloque\"      \"Resultado\"  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [120 × 3] (S3: tbl_df/tbl/data.frame)\n $ Tratamiento: chr [1:120] \"NPK Comercial\" \"NPK Comercial\" \"NPK Comercial\" \"NPK Comercial\" ...\n $ Bloque     : chr [1:120] \"A\" \"A\" \"A\" \"A\" ...\n $ Resultado  : num [1:120] 51.5 49.6 51.9 54.6 49.3 ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(DBCA$Resultado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  44.71   52.30   56.76   57.26   61.24   72.39 \n```\n\n\n:::\n:::\n\n\n### Convertir variables a factores\n\nPara garantizar un análisis correcto bajo el **Diseño de Bloques Completamente al Azar (DBCA)**, las variables **Tratamiento** y **Bloque** se convierten a factores en R. Esta conversión permite que el modelo ANOVA reconozca dichos elementos como variables categóricas y no como valores numéricos, asegurando una interpretación adecuada de los efectos experimentales.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDBCA$Tratamiento <- as.factor(DBCA$Tratamiento) \nDBCA$Bloque <- as.factor(DBCA$Bloque)\nstr (DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [120 × 3] (S3: tbl_df/tbl/data.frame)\n $ Tratamiento: Factor w/ 4 levels \"NPK + Bioinoculante\",..: 2 2 2 2 2 2 2 2 2 2 ...\n $ Bloque     : Factor w/ 3 levels \"A\",\"B\",\"C\": 1 1 1 1 1 1 1 1 1 1 ...\n $ Resultado  : num [1:120] 51.5 49.6 51.9 54.6 49.3 ...\n```\n\n\n:::\n:::\n\n\n## ANOVA para Diseño de Bloques Completamente al Azar -DBCA-\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodeloDBCA <- aov(Resultado ~ Tratamiento + Bloque, data = DBCA)\nsummary(modeloDBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nTratamiento   3   3602  1200.6 153.749 <2e-16 ***\nBloque        2     11     5.4   0.688  0.505    \nResiduals   114    890     7.8                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**Interpretación:** Los resultados del Análisis de Varianza (ANOVA) se ajustan a un modelo de Diseño de Bloques Completamente al Azar (DBCA), donde se evaluó el efecto del factor **Tratamiento** sobre una variable de **Resultado**, controlando la variabilidad mediante el factor **Bloque**.\n\n1\\. **Efecto del Tratamiento**. El análisis indica que el factor Tratamiento es altamente significativo sobre la variable de Resultado. Dado que el valor $\\text{p}$ es extremadamente pequeño (denotado por '\\*\\*\\*'), se **rechaza la hipótesis nula** de que no hay diferencias entre las medias de los tratamientos. Esto significa que existe una **diferencia estadísticamente significativa** en el Resultado al menos entre dos de los niveles de Tratamiento. **Grados de Libertad (Df):** 3. **Valor F (F value):** 153.749. **Valor p (**$\\text{Pr}(>F)$): $<2 \\text{e}-16$ (Menor que $0.001$)\n\n2\\. **Efecto del Bloque.** El análisis de la fuente de variación **Bloque** evalúa si el agrupamiento de las unidades experimentales fue efectivo para reducir la variabilidad del error. El valor $\\text{p}$ (0.505) es **mayor que el nivel de significancia** comúnmente utilizado ($\\alpha = 0.05$). Por lo tanto, el factor **Bloque no resultó ser significativo**. Esto indica que la variabilidad atribuida a las diferencias entre los Bloques no es mayor que la variabilidad aleatoria, sugiriendo que la inclusión del bloqueo no fue esencial o efectivo en este experimento particular.**Grados de Libertad (Df):** 2. **Valor F (F value):** 0.688. **Valor p (**$\\text{Pr}(>F)$): 0.505\n\n3\\. **Resumen del Modelo.** El factor **Tratamiento ejerce una influencia significativa** en el Resultado. Sin embargo, el factor **Bloque no contribuye significativamente** a explicar la variación del Resultado. Se requiere un análisis *post-hoc* (como Tukey o Sidak) para determinar cuáles pares específicos de Tratamientos difieren entre sí.\n\n## Verificación de supuestos\n\nEl ANOVA requiere cumplir tres supuestos básicos para garantizar la validez de los resultados. Ignorar estos supuestos puede generar conclusiones erróneas:\n\n1.  **Normalidad**, que implica que los datos se aproximen a una distribución normal, evaluada comúnmente con la prueba de **Shapiro--Wilk**.\n\n2.  **Homogeneidad de varianzas (homocedasticidad)**, que supone una variabilidad similar entre los grupos.\n\n3.  **Independencia de las observaciones**, donde los datos de un grupo no deben influir en los de otro.\n\n### Normalidad de residuos (Shapiro-Wilk)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- residuals(modeloDBCA)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  res\nW = 0.99559, p-value = 0.9725\n```\n\n\n:::\n:::\n\n\n**Interpretación:** La hipótesis nula de *Shapiro--Wilk* es que los datos provienen de una distribución normal , al tiempo que el  p-value = 0.9725 es  ≥ que 0.05, no hay evidencia para rechazar la normalidad, es por ello por lo que los residuos pueden considerarse normalmente distribuidos, lo cual respalda el supuesto de normalidad necesario para ANOVA.\n\n**Gráfico Q-Q de los residuos estandarizados**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(res)\nqqline(res, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-epub/unnamed-chunk-12-1.png)\n:::\n\n```{.r .cell-code}\nhist(res, main = \"Histograma de residuos\", xlab = \"Residuos\")\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-epub/unnamed-chunk-12-2.png)\n:::\n:::\n\n\n### Homocedasticidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(Resultado ~ Tratamiento, data = DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  Resultado by Tratamiento\nBartlett's K-squared = 7.4355, df = 3, p-value = 0.05924\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::leveneTest(Resultado ~ Tratamiento, data = DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   3  1.3691 0.2557\n      116               \n```\n\n\n:::\n\n```{.r .cell-code}\nfligner.test(Resultado ~ Tratamiento, data = DBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFligner-Killeen test of homogeneity of variances\n\ndata:  Resultado by Tratamiento\nFligner-Killeen:med chi-squared = 3.3125, df = 3, p-value = 0.3459\n```\n\n\n:::\n:::\n\n\n**Interpretación:** La hipótesis nula de *Bartlett* es que las varianzas entre los grupos son iguales, y como el *p-valor* =0.059 es ≥ 0.05, no se rechaza la hipótesis nula; no se rechaza la homogeneidad de varianzas, aunque está cerca del umbral. Esto sugiere que los datos cumplen razonablemente el supuesto de homocedasticidad, pero con un margen ajustado.\n\n### Gráfico de Residuos vs. Valores Ajustados\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Extraer valores ajustados y residuos del modelo DBCA\ndatos_homocedasticidad <- data.frame(\n  Valores_Ajustados = fitted(modeloDBCA),     # valores predichos del modelo\n  Residuos_Std = rstandard(modeloDBCA)        # residuos estandarizados\n)\n\n# 2. Gráfico de residuos vs valores ajustados\nggplot(datos_homocedasticidad, aes(x = Valores_Ajustados, y = Residuos_Std)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  theme_minimal() +\n  labs(\n    title = \"Gráfico de Residuos vs. Valores Ajustados (Homogeneidad de Varianzas)\",\n    x = \"Valores ajustados (predichos)\",\n    y = \"Residuos estandarizados\"\n  )\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-epub/unnamed-chunk-14-1.png)\n:::\n\n```{.r .cell-code}\n# Interpretación:\n# Los puntos deben dispersarse aleatoriamente alrededor de y = 0\n# sin formar patrones o conos, indicando homogeneidad de varianzas.\n```\n:::\n\n\n**Interpretación:** Tanto las pruebas estadísticas (**Bartlett, Levene y Fligner-Killeen**) como el **gráfico de residuos** indican que se cumple el supuesto de **homogeneidad de varianzas** en el modelo DBCA. Por tanto, el análisis de varianza (ANOVA) puede aplicarse de forma válida, ya que la variabilidad dentro de los grupos de tratamiento es similar y no se detectan violaciones importantes de este supuesto.\n\n### Independencia de residuos\n\nEl **Durbin--Watson test** evalúa la **independencia de los residuos**:\n\n**Hipótesis nula (H₀):** los residuos son independientes.\\\n**Hipótesis alternativa (H₁):** los residuos están autocorrelacionados.\\\n\\\nSi el **p-value \\> 0.05**, **no se rechaza H₀**, por lo que **los residuos son independientes** (el supuesto se cumple). Si el **p-value \\< 0.05**, existe **autocorrelación** y el supuesto no se cumple.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndwtest(modeloDBCA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tDurbin-Watson test\n\ndata:  modeloDBCA\nDW = 2.042, p-value = 0.4159\nalternative hypothesis: true autocorrelation is greater than 0\n```\n\n\n:::\n:::\n\n\nInterpretación: Debido a que el **valor** $\\text{p}$ ($0.4159$) es mucho mayor que $0.05$, **no hay evidencia estadística suficiente para rechazar la hipótesis nula**. Se concluye, por lo tanto, que el supuesto de **independencia de los residuos** se cumple satisfactoriamente en el modelo DBCA. La cercanía del estadístico DW (2.042) al valor ideal de 2.0 refuerza esta conclusión.\n\n## **Pruebas aposteriori**\n\nEn el marco del **Diseño de Bloques Completamente al Azar (DBCA)** aplicado al cultivo de frijol, una vez verificados los supuestos de **normalidad** y **homogeneidad de varianzas**, se procede a realizar las **pruebas de comparación múltiple de medias**. Estas pruebas, como las de **Tukey** o **Duncan**, permiten identificar qué tratamientos presentan diferencias significativas en su efecto sobre la altura de las plantas.\n\nEl uso del DBCA contribuye a **reducir la variabilidad experimental** al controlar los factores externos mediante el bloqueo, lo que incrementa la **precisión y confiabilidad** de las comparaciones. En consecuencia, las diferencias observadas entre tratamientos reflejan principalmente los **efectos reales de las condiciones aplicadas**, y no la influencia del azar o de fuentes de variación no controladas.\n\n### Tukey HSD (agrupamiento con letras)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHSD.test(modeloDBCA, \"Tratamiento\", group = TRUE, console = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStudy: modeloDBCA ~ \"Tratamiento\"\n\nHSD Test for Resultado \n\nMean Square Error:  7.808829 \n\nTratamiento,  means\n\n                       Resultado      std  r        se   Min   Max     Q25\nNPK + Bioinoculante     54.25933 2.395591 30 0.5101904 49.26 58.09 52.9100\nNPK Comercial           50.29667 2.453096 30 0.5101904 44.71 54.74 48.5975\nOrgánico + NPK          64.78000 3.621806 30 0.5101904 57.14 72.39 62.1700\nOrganico + NPK (50:50)  59.71300 2.488591 30 0.5101904 55.73 65.66 58.2425\n                          Q50     Q75\nNPK + Bioinoculante    54.045 55.9275\nNPK Comercial          50.080 51.8625\nOrgánico + NPK         65.070 66.9650\nOrganico + NPK (50:50) 59.480 61.0025\n\nAlpha: 0.05 ; DF Error: 114 \nCritical Value of Studentized Range: 3.687325 \n\nMinimun Significant Difference: 1.881238 \n\nTreatments with the same letter are not significantly different.\n\n                       Resultado groups\nOrgánico + NPK          64.78000      a\nOrganico + NPK (50:50)  59.71300      b\nNPK + Bioinoculante     54.25933      c\nNPK Comercial           50.29667      d\n```\n\n\n:::\n:::\n\n\n**Interpretación:** La prueba de **Tukey HSD**, aplicada al **Diseño de Bloques Completamente al Azar (DBCA)** para la variable *altura de las plantas de frijol*, indica que el **Tratamiento 4** obtuvo la mayor media (64.78 cm; grupo *a*), seguido del **Tratamiento 3** (59.71 cm; grupo *b*), luego el **Tratamiento 2** (54.26 cm; grupo *c*), y finalmente el **Tratamiento 1** (50.29 cm; grupo *d*), con la menor media. El valor de la **diferencia mínima significativa (HSD)** fue de **1.88**, más estricto que el obtenido con la prueba **LSD** (1.43). Aun así, los tratamientos mantienen una **separación completa**, sin letras compartidas entre grupos, lo que evidencia que **todas las medias difieren significativamente entre sí** al nivel de confianza del 95 %.\n\nEstos resultados confirman que los tratamientos ejercieron **efectos claramente diferenciados** sobre la altura de las plantas, y que las diferencias observadas **no se deben al azar**. La consistencia entre las pruebas de **LSD y Tukey** respalda la **robustez y confiabilidad del experimento**.\n\n### Comparaciones múltiples con LSD\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout_LSD <- LSD.test(modeloDBCA, \"Tratamiento\", group = TRUE, console = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStudy: modeloDBCA ~ \"Tratamiento\"\n\nLSD t Test for Resultado \n\nMean Square Error:  7.808829 \n\nTratamiento,  means and individual ( 95 %) CI\n\n                       Resultado      std  r        se      LCL      UCL   Min\nNPK + Bioinoculante     54.25933 2.395591 30 0.5101904 53.24865 55.27002 49.26\nNPK Comercial           50.29667 2.453096 30 0.5101904 49.28598 51.30735 44.71\nOrgánico + NPK          64.78000 3.621806 30 0.5101904 63.76932 65.79068 57.14\nOrganico + NPK (50:50)  59.71300 2.488591 30 0.5101904 58.70232 60.72368 55.73\n                         Max     Q25    Q50     Q75\nNPK + Bioinoculante    58.09 52.9100 54.045 55.9275\nNPK Comercial          54.74 48.5975 50.080 51.8625\nOrgánico + NPK         72.39 62.1700 65.070 66.9650\nOrganico + NPK (50:50) 65.66 58.2425 59.480 61.0025\n\nAlpha: 0.05 ; DF Error: 114\nCritical Value of t: 1.980992 \n\nleast Significant Difference: 1.429322 \n\nTreatments with the same letter are not significantly different.\n\n                       Resultado groups\nOrgánico + NPK          64.78000      a\nOrganico + NPK (50:50)  59.71300      b\nNPK + Bioinoculante     54.25933      c\nNPK Comercial           50.29667      d\n```\n\n\n:::\n:::\n\n\n**Interpretación:** El resultado de la prueba **LSD (Least Significant Difference)** aplicada al **Diseño de Bloques Completamente al Azar (DBCA)** para la variable *altura de las plantas de frijol* evidencia una clara **separación de medias entre tratamientos**. El **Tratamiento 4** presentó la mayor altura promedio (64.78 cm; grupo *a*), seguido del **Tratamiento 3** (59.71 cm; grupo *b*), el **Tratamiento 2** (54.26 cm; grupo *c*) y finalmente el **Tratamiento 1** (50.29 cm; grupo *d*), con la menor media. El valor de la **diferencia mínima significativa (LSD)** fue de **1.43**, indicando que cualquier diferencia superior a este umbral es **estadísticamente significativa al 95 % de confianza**. Ninguno de los tratamientos comparte letra, lo que confirma que **todos difieren significativamente entre sí**. Estos resultados respaldan que los tratamientos generaron **efectos distintos y consistentes** sobre la altura de las plantas de frijol, más allá de la variabilidad natural controlada mediante los bloques.\n\n### Visualización de resultados\n\n#### Caja y Bigote (Boxplot en ggplot2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(DBCA, aes(x = Tratamiento, y = Resultado, fill = Tratamiento)) + geom_boxplot() + theme_minimal() + labs( title = \"Distribución del resultado por tratamiento\", x = \"Tratamiento\", y = \"Resultado\")\n```\n\n::: {.cell-output-display}\n![](Chapter_05_files/figure-epub/unnamed-chunk-18-1.png)\n:::\n:::\n\n\n**Interpretación:** La gráfica muestra la **distribución de los valores de altura de las plantas de *Phaseolus vulgaris*** bajo cuatro tratamientos de fertilización evaluados mediante un **Diseño de Bloques Completamente al Azar (DBCA)**. Se observa una **tendencia ascendente** en la mediana y en el rango de los resultados desde **NPK Comercial** hasta **Orgánico + NPK**, lo que indica un efecto progresivamente favorable de los tratamientos sobre el crecimiento de las plantas.\n\nEl **tratamiento Orgánico + NPK** presenta las mayores alturas promedio, seguido de **Orgánico + NPK (50:50)**, **NPK + Bioinoculante** y finalmente **NPK Comercial**, que registra los valores más bajos. La **variabilidad dentro de cada grupo** se mantiene controlada, aunque se identifica un **valor atípico en el tratamiento Orgánico + NPK (50:50)**, algo común en ensayos biológicos debido a la variación natural entre individuos.\n\nEstos resultados **coinciden con las pruebas de comparación de medias (LSD y Tukey)**, en las que los tratamientos se agrupan en **cuatro categorías estadísticas distintas (a, b, c y d)**, confirmando que las diferencias en altura entre los tratamientos son **estadísticamente significativas** y reflejan **efectos reales** de las condiciones de fertilización aplicadas.\n",
    "supporting": [
      "Chapter_05_files\\figure-epub"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}