{
  "hash": "0c8f88cca5ff22b44f2da475b038c664",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Capitulo 6 Diseño longitudinal (ANOVA de medidas repetidas)\"\n---\n\n## Problema\n\n::: callout-note\nEl trabajo de grado desarrollado por [@FuentesRicaurte2024]analizó el potencial de tres géneros de **hongos mitospóricos**, entre ellos *Aspergillus* sp. (As), para la **bioacumulación de los metales pesados cadmio (Cd) y plomo (Pb)** en su micelio. Para ello, se emplearon medios de cultivo **caldo papa dextrosa (CPD)** suplementados con concentraciones de **100, 150 y 200 mg/L** de cada metal, considerando el **tiempo** como un factor determinante en el proceso de bioacumulación.\n\nLa **cuantificación del metal retenido en el micelio** se realizó mediante **espectrometría de absorción atómica**, técnica que permitió evaluar la eficiencia de remoción. Los resultados mostraron que *Aspergillus* sp. fue el género más eficiente en la **bioacumulación de plomo (Pb)**, alcanzando hasta **94,38 % de remoción** a 200 mg/L, mientras que para **cadmio (Cd)** se obtuvo una remoción del **92,82 %**.\n\n[![(A): Micelio de cepa ambiental de Aspergillus sp. en medio de cultivo PDA. (B): Microscopia cepa de Aspergillus sp. tomada a 40X por medio de tinción de impronta con KOH 10%.](images/5_DMRT/DMRT_Aspergillus.png){fig-alt=\"Fuentes-Ricaurte, H.  (2024).  Evaluación de la Bioacumulación de Cadmio y Plomo con Cepas de Hongos Mitospóricos de Origen Ambiental. Universidad de Santander.\"}](https://repositorio.udes.edu.co/handle/001/11020)\n:::\n\n## Estructura de la base de datos\n\nLos datos analizados provienen de un **experimento microbiológico** diseñado para evaluar la **bioacumulación de plomo (Pb)** por *Aspergillus* sp. bajo distintas concentraciones en el medio de cultivo.\\\nLa base de datos está compuesta por **cuatro columnas principales**, que describen las variables medidas en el ensayo: **Tiempo**, **Tratamiento**, **Repetición** y **Resultado**.\n\n::: {#tbl-estructura .table caption=\"Estructura de la base de datos utilizada en el análisis.\"}\n| **Variable**    | **Tipo de variable** | **Descripción**                                                                                                                                                     |\n|-----------|-----------|-------------------------------------------------|\n| **Tiempo**      | Categórica           | Días después de la inoculación (ddi). Representa los momentos de medición del experimento.                                                                          |\n| **Tratamiento** | Categórica           | Inoculación de *Aspergillus* sp. en medios de cultivo suplementados con 100, 150 y 200 mg/L de Pb.                                                                  |\n| **Repetición**  | Numérica             | Identifica el número de repetición del tratamiento (1, 2, 3).                                                                                                       |\n| **Resultado**   | Continua (numérica)  | Variable cuantitativa que expresa el valor observado del experimento. Puede tomar cualquier valor dentro de un rango, incluidos decimales (p. ej., 75.6, 4.1, 0.2). |\n:::\n\nCada combinación de **Tratamiento × Tiempo** se evaluó por triplicado, lo que permitió analizar la **variabilidad experimental** y aplicar un **modelo mixto lineal de medidas repetidas** para estudiar el efecto del **tiempo** y la **concentración de Pb** sobre la **bioacumulación**.\n\nEl experimento cumple con las condiciones que caracterizan un **diseño de medidas repetidas**, dado que las mismas unidades experimentales (*frascos de cultivo*) fueron evaluadas en distintos momentos del tiempo (0, 10, 15 y 20 días después de la inoculación). En este contexto, se empleó un **modelo mixto lineal (LME)**, el cual permite analizar los **efectos fijos** del *Tratamiento* (concentración de Pb) y del *Tiempo*, considerando simultáneamente la **variabilidad aleatoria** asociada a cada frasco (*Id*).\n\nEste enfoque resulta especialmente adecuado para **datos dependientes en el tiempo**, ya que controla la **correlación entre observaciones repetidas** dentro de la misma unidad experimental y proporciona **inferencias más precisas y robustas** que un ANOVA tradicional.\n\n::: {#tbl-estructura-mixto .table caption=\"Estructura del diseño experimental y justificación del modelo mixto lineal de medidas repetidas.\"}\n| **Elemento**            | **Descripción**                                                              | **Tipo**              |\n|----------------|-----------------------------------------|----------------|\n| **Unidad experimental** | Frasco o cultivo individual (*Id*).                                          | Efecto **aleatorio**  |\n| **Factores fijos**      | \\- Concentración de Pb (*Tratamiento*)<br>- Tiempo de incubación (*Tiempo*). | Efectos **fijos**     |\n| **Variable respuesta**  | Bioacumulación de Pb (*Resultado*).                                          | Continua              |\n| **Estructura temporal** | Mismas unidades (*frascos*) medidas en varios tiempos (0, 10, 15 y 20 ddi).  | **Medidas repetidas** |\n:::\n\n## Diseño: Tratamiento (factor entre sujetos) x Tiempo (factor intra-sujetos)\n\n### Cargar las librerias necesarias para el análisis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\n  library(readxl)\n  library(nlme)\n  library(ggplot2)\n  library(emmeans)\n  library(dplyr)\n  library(multcomp)\n  library(multcompView)\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readxl' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'nlme' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'emmeans' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'multcomp' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'mvtnorm' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'survival' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'TH.data' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'multcompView' was built under R version 4.3.3\n```\n\n\n:::\n:::\n\n\n### Importar datos desde Excel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nDMRT <- read_excel(\"C:/R-Proyectos/r-para-mi/data/DMRT_Hongos/DMRT.xlsx\")\n```\n:::\n\n\n### Exploración inicial y estructura de la base de datos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(DMRT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Id\"          \"Tiempo\"      \"Tratamiento\" \"Repeticion\"  \"Resultado\"  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(DMRT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [36 x 5] (S3: tbl_df/tbl/data.frame)\n $ Id         : chr [1:36] \"f1100\" \"f2100\" \"f3100\" \"f1100\" ...\n $ Tiempo     : chr [1:36] \"0 ddi\" \"0 ddi\" \"0 ddi\" \"10 ddi\" ...\n $ Tratamiento: chr [1:36] \"As 100 mg/L Pb\" \"As 100 mg/L Pb\" \"As 100 mg/L Pb\" \"As 100 mg/L Pb\" ...\n $ Repeticion : num [1:36] 1 2 3 1 2 3 1 2 3 1 ...\n $ Resultado  : num [1:36] 0 0 0 4.5 9.7 12.8 63.1 58.3 67.7 82.1 ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(DMRT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 5\n  Id    Tiempo Tratamiento    Repeticion Resultado\n  <chr> <chr>  <chr>               <dbl>     <dbl>\n1 f1100 0 ddi  As 100 mg/L Pb          1       0  \n2 f2100 0 ddi  As 100 mg/L Pb          2       0  \n3 f3100 0 ddi  As 100 mg/L Pb          3       0  \n4 f1100 10 ddi As 100 mg/L Pb          1       4.5\n5 f2100 10 ddi As 100 mg/L Pb          2       9.7\n6 f3100 10 ddi As 100 mg/L Pb          3      12.8\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(DMRT$Resultado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   3.375  55.725  47.017  78.800  95.650 \n```\n\n\n:::\n:::\n\n\n### Verificación del equilibrio del diseño experimental\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)  # Contar el número de observaciones por combinación de Tratamiento × Tiempo  \nDMRT %>% count(Tratamiento, Tiempo) %>% arrange(Tratamiento, Tiempo) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 x 3\n   Tratamiento    Tiempo     n\n   <chr>          <chr>  <int>\n 1 As 100 mg/L Pb 0 ddi      3\n 2 As 100 mg/L Pb 10 ddi     3\n 3 As 100 mg/L Pb 15 ddi     3\n 4 As 100 mg/L Pb 20 ddi     3\n 5 As 150 mg/L Pb 0 ddi      3\n 6 As 150 mg/L Pb 10 ddi     3\n 7 As 150 mg/L Pb 15 ddi     3\n 8 As 150 mg/L Pb 20 ddi     3\n 9 As 200 mg/L Pb 0 ddi      3\n10 As 200 mg/L Pb 10 ddi     3\n11 As 200 mg/L Pb 15 ddi     3\n12 As 200 mg/L Pb 20 ddi     3\n```\n\n\n:::\n:::\n\n\n### Convertir variables categóricas a factores\n\nAntes de realizar el análisis de varianza (ANOVA), es necesario convertir las variables categóricas ---como los tratamientos o los tiempos de muestreo--- en **factores**, ya que este tipo de análisis requiere que los grupos experimentales sean interpretados como categorías y no como valores numéricos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDMRT$Tratamiento <- as.factor(DMRT$Tratamiento)  # Efecto fijo 1: concentración de Pb\nDMRT$Tiempo <- as.factor(DMRT$Tiempo)            # Efecto fijo 2: tiempo de exposición\nDMRT$Id <- as.factor(DMRT$Id)                    # Efecto aleatorio: frasco o unidad experimental\n\nstr(DMRT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [36 x 5] (S3: tbl_df/tbl/data.frame)\n $ Id         : Factor w/ 9 levels \"f1100\",\"f1150\",..: 1 4 7 1 4 7 1 4 7 1 ...\n $ Tiempo     : Factor w/ 4 levels \"0 ddi\",\"10 ddi\",..: 1 1 1 2 2 2 3 3 3 4 ...\n $ Tratamiento: Factor w/ 3 levels \"As 100 mg/L Pb\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ Repeticion : num [1:36] 1 2 3 1 2 3 1 2 3 1 ...\n $ Resultado  : num [1:36] 0 0 0 4.5 9.7 12.8 63.1 58.3 67.7 82.1 ...\n```\n\n\n:::\n:::\n\n\n### Ajuste del modelo mixto lineal (efectos fijos + aleatorios)\n\n### Modelo mixto lineal de medidas repetidas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nlme)\n\n# Ajuste del modelo mixto lineal (efectos fijos + aleatorios)\nmodelo_mixto <- lme(\n  Resultado ~ Tratamiento * Tiempo,  # efectos fijos\n  random = ~1 | Id,                  # efecto aleatorio por frasco\n  data = DMRT                        # conjunto de datos\n)\n```\n:::\n\n\n**Interpretación:**\\\nEste modelo mixto se usa para analizar datos donde se repiten las mediciones (por ejemplo, la bioacumulación de plomo en diferentes tiempos dentro del mismo frasco o individuo).\n\n-   **Efectos fijos:** `Tratamiento` y `Tiempo`, además de su interacción (`Tratamiento*Tiempo`), permiten evaluar si existen diferencias sistemáticas entre tratamientos, entre momentos de tiempo y si el efecto del tratamiento cambia a lo largo del tiempo.\n\n-   **Efecto aleatorio:** `~1 | Id` indica que se considera la variabilidad individual de cada frasco o unidad experimental, controlando así la correlación entre medidas repetidas del mismo sujeto.\n\n-   Este tipo de modelo mejora la precisión del análisis porque separa la variabilidad intra-sujeto de la variabilidad entre sujetos, algo que un ANOVA tradicional no podría hacer adecuadamente.\n\n**Análisis de la Varianza - ANOVA**\n\nEl **análisis de varianza (ANOVA)** es una herramienta estadística fundamental en las investigaciones **microbiológicas y ambientales**, ya que permite determinar si las diferencias observadas en la **bioacumulación de plomo (Pb)** se deben realmente a los **tratamientos experimentales** y no al efecto del azar. Cuando se cumplen los **supuestos de normalidad y homogeneidad de varianzas**, el ANOVA ofrece **inferencias sólidas y confiables**, lo que fortalece la **validez interna del experimento** y respalda la interpretación de los resultados obtenidos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Resultados del ANOVA del modelo\nanova(modelo_mixto)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   numDF denDF  F-value p-value\n(Intercept)            1    18 6228.224  <.0001\nTratamiento            2     6   66.120   1e-04\nTiempo                 3    18 1636.285  <.0001\nTratamiento:Tiempo     6    18   40.052  <.0001\n```\n\n\n:::\n:::\n\n\n**Interpretación:**\n\nEl intercepto no presenta un interés biológico directo, ya que únicamente funciona como punto de referencia dentro del modelo estadístico. En cuanto al factor **tratamiento (p \\< 0.0001)**, se observaron diferencias significativas entre los distintos tratamientos, lo que indica que la bioacumulación de plomo varía de manera notable según el tipo de tratamiento aplicado. Por otro lado, el **tiempo (p \\< 0.0001)** también mostró un efecto significativo sobre la respuesta, evidenciando que los niveles de bioacumulación cambian de forma importante a lo largo del periodo de evaluación. Finalmente, la **interacción entre tratamiento y tiempo (p \\< 0.0001)** resultó significativa, lo que sugiere que el efecto de los tratamientos depende del momento de medición; es decir, los tratamientos no presentan el mismo comportamiento en todos los tiempos analizados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Resumen detallado del modelo\nsummary(modelo_mixto)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed-effects model fit by REML\n  Data: DMRT \n       AIC      BIC    logLik\n  163.4999 179.9926 -67.74993\n\nRandom effects:\n Formula: ~1 | Id\n        (Intercept) Residual\nStdDev:    1.010727 2.948069\n\nFixed effects:  Resultado ~ Tratamiento * Tiempo \n                                          Value Std.Error DF  t-value p-value\n(Intercept)                             0.00000  1.799322 18  0.00000  1.0000\nTratamientoAs 150 mg/L Pb               0.00000  2.544625  6  0.00000  1.0000\nTratamientoAs 200 mg/L Pb               0.00000  2.544625  6  0.00000  1.0000\nTiempo10 ddi                            9.00000  2.407088 18  3.73896  0.0015\nTiempo15 ddi                           63.03333  2.407088 18 26.18655  0.0000\nTiempo20 ddi                           86.56667  2.407088 18 35.96323  0.0000\nTratamientoAs 150 mg/L Pb:Tiempo10 ddi 21.77778  3.404136 18  6.39745  0.0000\nTratamientoAs 200 mg/L Pb:Tiempo10 ddi 45.93333  3.404136 18 13.49339  0.0000\nTratamientoAs 150 mg/L Pb:Tiempo15 ddi -5.74444  3.404136 18 -1.68749  0.1088\nTratamientoAs 200 mg/L Pb:Tiempo15 ddi 12.25000  3.404136 18  3.59856  0.0021\nTratamientoAs 150 mg/L Pb:Tiempo20 ddi  6.36667  3.404136 18  1.87027  0.0778\nTratamientoAs 200 mg/L Pb:Tiempo20 ddi  7.81667  3.404136 18  2.29623  0.0339\n Correlation: \n                                       (Intr) TA15mP TA20mP Tmp10d Tmp15d\nTratamientoAs 150 mg/L Pb              -0.707                            \nTratamientoAs 200 mg/L Pb              -0.707  0.500                     \nTiempo10 ddi                           -0.669  0.473  0.473              \nTiempo15 ddi                           -0.669  0.473  0.473  0.500       \nTiempo20 ddi                           -0.669  0.473  0.473  0.500  0.500\nTratamientoAs 150 mg/L Pb:Tiempo10 ddi  0.473 -0.669 -0.334 -0.707 -0.354\nTratamientoAs 200 mg/L Pb:Tiempo10 ddi  0.473 -0.334 -0.669 -0.707 -0.354\nTratamientoAs 150 mg/L Pb:Tiempo15 ddi  0.473 -0.669 -0.334 -0.354 -0.707\nTratamientoAs 200 mg/L Pb:Tiempo15 ddi  0.473 -0.334 -0.669 -0.354 -0.707\nTratamientoAs 150 mg/L Pb:Tiempo20 ddi  0.473 -0.669 -0.334 -0.354 -0.354\nTratamientoAs 200 mg/L Pb:Tiempo20 ddi  0.473 -0.334 -0.669 -0.354 -0.354\n                                       Tmp20d TA150m/LP:T10d TA200m/LP:T10d\nTratamientoAs 150 mg/L Pb                                                  \nTratamientoAs 200 mg/L Pb                                                  \nTiempo10 ddi                                                               \nTiempo15 ddi                                                               \nTiempo20 ddi                                                               \nTratamientoAs 150 mg/L Pb:Tiempo10 ddi -0.354                              \nTratamientoAs 200 mg/L Pb:Tiempo10 ddi -0.354  0.500                       \nTratamientoAs 150 mg/L Pb:Tiempo15 ddi -0.354  0.500          0.250        \nTratamientoAs 200 mg/L Pb:Tiempo15 ddi -0.354  0.250          0.500        \nTratamientoAs 150 mg/L Pb:Tiempo20 ddi -0.707  0.500          0.250        \nTratamientoAs 200 mg/L Pb:Tiempo20 ddi -0.707  0.250          0.500        \n                                       TA150m/LP:T15d TA200m/LP:T15d\nTratamientoAs 150 mg/L Pb                                           \nTratamientoAs 200 mg/L Pb                                           \nTiempo10 ddi                                                        \nTiempo15 ddi                                                        \nTiempo20 ddi                                                        \nTratamientoAs 150 mg/L Pb:Tiempo10 ddi                              \nTratamientoAs 200 mg/L Pb:Tiempo10 ddi                              \nTratamientoAs 150 mg/L Pb:Tiempo15 ddi                              \nTratamientoAs 200 mg/L Pb:Tiempo15 ddi  0.500                       \nTratamientoAs 150 mg/L Pb:Tiempo20 ddi  0.500          0.250        \nTratamientoAs 200 mg/L Pb:Tiempo20 ddi  0.250          0.500        \n                                       TA150m/LP:T2d\nTratamientoAs 150 mg/L Pb                           \nTratamientoAs 200 mg/L Pb                           \nTiempo10 ddi                                        \nTiempo15 ddi                                        \nTiempo20 ddi                                        \nTratamientoAs 150 mg/L Pb:Tiempo10 ddi              \nTratamientoAs 200 mg/L Pb:Tiempo10 ddi              \nTratamientoAs 150 mg/L Pb:Tiempo15 ddi              \nTratamientoAs 200 mg/L Pb:Tiempo15 ddi              \nTratamientoAs 150 mg/L Pb:Tiempo20 ddi              \nTratamientoAs 200 mg/L Pb:Tiempo20 ddi  0.500       \n\nStandardized Within-Group Residuals:\n        Min          Q1         Med          Q3         Max \n-2.36609032 -0.24438078  0.08881768  0.33881909  1.57247026 \n\nNumber of Observations: 36\nNumber of Groups: 9 \n```\n\n\n:::\n:::\n\n\n## \n\n## Verificación de Supuestos\n\nLa verificación de los supuestos estadísticos es esencial para garantizar la validez del ANOVA. Primero se debe evaluar la **normalidad de los residuos** mediante la prueba de **Shapiro-Wilk**, que determina si las desviaciones respecto a la normalidad son significativas. Además, es necesario comprobar la **homogeneidad de varianzas** con la prueba de **Bartlett**, asegurando que las comparaciones entre tratamientos no estén sesgadas por diferencias en la variabilidad. Si alguno de estos supuestos no se cumple, se recomienda aplicar **transformaciones de los datos** o emplear **modelos con varianzas heterogéneas**.\n\n### Normalidad de residuos del modelo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresiduos <- residuals(modelo_mixto, type = \"normalized\")\n\n# Normalidad de residuos (Shapiro-Wilk)\nshapiro.test(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuos\nW = 0.95276, p-value = 0.1277\n```\n\n\n:::\n:::\n\n\n**Interpretación:** La prueba de normalidad de Shapiro-Wilk mostró un valor de **p = 0.1277**, superior a 0.05, lo que indica que **no se rechaza la hipótesis nula de normalidad**. Por lo tanto, se concluye que los **residuos se distribuyen de manera aproximadamente normal**, cumpliendo con este supuesto del modelo.\n\n**Gráfico Q-Q de los residuos estandarizados**\n\nEl gráfico Q-Q es el método estándar para evaluar la normalidad.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cargar la librería necesaria para el modelo (si no está cargada)\n# library(nlme) \nlibrary(ggplot2)\n\n# 1. Extraer los residuos estandarizados del modelo\nresiduos_std <- residuals(modelo_mixto, type = \"normalized\")\n\n# 2. Crear un marco de datos con los residuos estandarizados\ndatos_qq <- data.frame(\n  Residuos_Std = residuos_std,\n  Teoricos = qnorm(ppoints(length(residuos_std)))\n)\n\n# 3. Generar el gráfico Q-Q\nggplot(datos_qq, aes(x = Teoricos, y = Residuos_Std)) +\n  geom_point(alpha = 0.6) +\n  geom_abline(intercept = 0, slope = 1, color = \"red\", linetype = \"dashed\") +\n  theme_minimal() +\n  labs(\n    title = \"Gráfico Q-Q para la Normalidad de los Residuos\",\n    x = \"Cuantiles Teóricos Normales\",\n    y = \"Residuos Estandarizados del Modelo\"\n  )\n```\n\n::: {.cell-output-display}\n![](Chapter_06_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Interpretación: Los puntos deben seguir de cerca la línea roja.\n\n# --- B. Prueba de Shapiro-Wilk (Opcional, pero complementaria) ---\n# shapiro.test(residuos_std) \n# Interpretación: Si el valor p > 0.05, no se rechaza la normalidad.\n```\n:::\n\n\n### Homocedasticidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Homogeneidad de varianzas (Bartlett)\nbartlett.test(Resultado ~ Tratamiento, data = DMRT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  Resultado by Tratamiento\nBartlett's K-squared = 0.036607, df = 2, p-value = 0.9819\n```\n\n\n:::\n:::\n\n\n**Interpretación:** La prueba de homogeneidad de varianzas de Bartlett arrojó un valor de **p = 0.9819**, muy superior a 0.05, por lo que **no se rechaza la hipótesis nula de igualdad de varianzas**. Esto indica que las **varianzas entre los tratamientos son homogéneas**, cumpliéndose así el supuesto de homogeneidad requerido para el análisis.\n\n### Gráfico de Residuos vs. Valores Ajustados\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Extraer los valores ajustados (predichos) y los residuos\ndatos_homocedasticidad <- data.frame(\n  Valores_Ajustados = fitted(modelo_mixto),\n  Residuos_Std = residuals(modelo_mixto, type = \"normalized\")\n)\n\n# 2. Generar el gráfico\nggplot(datos_homocedasticidad, aes(x = Valores_Ajustados, y = Residuos_Std)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  theme_minimal() +\n  labs(\n    title = \"Gráfico de Residuos vs. Valores Ajustados (Homocedasticidad)\",\n    x = \"Valores Ajustados (Predichos)\",\n    y = \"Residuos Estandarizados\"\n  )\n```\n\n::: {.cell-output-display}\n![](Chapter_06_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Interpretación: Los puntos deben dispersarse aleatoriamente alrededor de la línea y=0, \n# sin formar patrones de embudo o conos.\n```\n:::\n\n\n### Independencia/Estructura de Correlación\n\nEste supuesto verifica si la dependencia temporal restante dentro de cada unidad experimental (`Id`) ha sido modelada correctamente.\n\n### Gráfico de Residuos vs. Tiempo por Unidad Experimental\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Preparar el marco de datos con Residuos, Tiempo e Id\ndatos_independencia <- data.frame(\n  Tiempo = modelo_mixto$data$Tiempo,\n  Id = modelo_mixto$data$Id,\n  Residuos = residuals(modelo_mixto, type = \"normalized\")\n)\n\n# 2. Generar el gráfico\nggplot(datos_independencia, aes(x = Tiempo, y = Residuos, group = Id)) +\n  geom_line(alpha = 0.3) +\n  geom_point(aes(color = Id), show.legend = FALSE) + # Color por Id para diferenciación\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  theme_minimal() +\n  labs(\n    title = \"Evaluación de la Correlación Temporal de los Residuos\",\n    subtitle = \"Si hay patrones, la estructura de correlación debe revisarse\",\n    x = \"Tiempo (ddi)\",\n    y = \"Residuos Estandarizados\"\n  )\n```\n\n::: {.cell-output-display}\n![](Chapter_06_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Interpretación: Si hay un patrón de correlación visible (líneas que siguen una forma \n# similar a lo largo del tiempo), el modelo podría necesitar una estructura de \n# correlación explícita (p. ej., corAR1) añadida al objeto lme.\n```\n:::\n\n\n**Interpretación:** El análisis de los residuos indica una **violación del supuesto de independencia temporal**. Se observa un **patrón sistemático** (subida y bajada) en los residuos a lo largo del tiempo que se repite en las unidades experimentales, lo cual sugiere que el modelo actual, con solo una intercepción aleatoria, **no está capturando adecuadamente la correlación temporal** entre las mediciones. Para obtener estimaciones de error estándar válidas y garantizar la fiabilidad de las comparaciones post-hoc, es **obligatorio reajustar el modelo lineal mixto** incluyendo una **estructura de correlación explícita** (como AR(1)).\n\n## **Pruebas aposteriori**\n\n### LSD (sin ajuste, equivalente a prueba de Fisher LSD)\n\n```{r} emmeans_trat_tiempo <- emmeans(modelo_mixto, ~ Tratamiento | Tiempo)  cld_LSD <- multcomp::cld(emmeans_trat_tiempo,                          adjust = \"none\",   # LSD no ajusta comparaciones                          Letters = letters,                         alpha = 0.05) print(cld_LSD)}\n```\n\n### Comparaciones Post-Hoc (EMMEANS + SIDAK)\n\n```{r} #| label: posthoc-plot #| echo: false #| message: false #| warning: true  # Si no existe, calcula EMMEANS + CLD if (!exists(\"cld_trat_tiempo\")) {   emmeans_trat_tiempo <- emmeans(modelo_mixto, ~ Tratamiento | Tiempo)   cld_trat_tiempo <- multcomp::cld(     emmeans_trat_tiempo,     adjust = \"sidak\",     Letters = letters,     alpha = 0.05   ) }  # Convertir a data.frame para ggplot plot_data <- as.data.frame(cld_trat_tiempo)  # Comprobaciones mínimas (fallan temprano si algo no está) req_cols <- c(\"Tiempo\",\"Tratamiento\",\"emmean\",\"lower.CL\",\"upper.CL\",\".group\") stopifnot(all(req_cols %in% names(plot_data)))  # Limpieza y formatos plot_data$Tiempo  <- factor(plot_data$Tiempo) plot_data$.group  <- trimws(plot_data$.group)  # Gráfico pd <- position_dodge(0.45) ggplot(plot_data, aes(x = Tiempo, y = emmean,                       color = Tratamiento, group = Tratamiento)) +   geom_line(position = pd, linewidth = 1.1) +   geom_point(position = pd, size = 3) +   geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),                 width = 0.2, position = pd) +   geom_text(aes(label = .group), vjust = -0.8,             position = pd, show.legend = FALSE) +   theme_minimal() +   labs(title = \"Comparaciones post-hoc (Sidak) para Tratamiento × Tiempo\",        x = \"Tiempo\",        y = \"Bioacumulación de PB (medias ± IC95%)\")}\n```\n\n### Tratamientos dentro de cada tiempo\n\n### Análisis de la Interacción Tratamiento × Tiempo\n\nEste análisis se centra en identificar cuáles tratamientos difieren significativamente entre sí en cada punto de tiempo evaluado. Se utilizó el método de Letras (agrupamiento) donde **los tratamientos que comparten la misma letra en la columna `.group` no son significativamente diferentes entre sí** para un nivel de significancia de $\\alpha = 0.05$.\n\n⏳ **Tiempo = 0 ddi**\n\n-   **Resultados:** En este momento inicial, los tres tratamientos (As 100 mg/L Pb, As 200 mg/L Pb, y As 150 mg/L Pb) se encuentran en el **mismo grupo ('a')**.\n\n-   **Conclusión:** No existe una diferencia significativa en la media marginal estimada (`emmean`) entre los tres tratamientos al inicio del experimento.\n\n⏳ **Tiempo = 10 ddi**\n\n-   **Resultados:** Se observa una clara separación de los tratamientos en tres grupos distintos.\n\n    **As 100 mg/L Pb** forma el grupo más bajo ('a') con una media de 9.0.\\\n    **As 150 mg/L Pb** forma el grupo intermedio ('b') con una media de 30.8.\\\n    **As 200 mg/L Pb** forma el grupo más alto ('c') con una media de 54.9.\n\n    **Conclusión:** A los 10 días, **todos los tratamientos son significativamente diferentes entre sí**. El efecto o respuesta medida es significativamente mayor a medida que la concentración de plomo (Pb) aumenta (100 \\< 150 \\< 200).\n\n⏳ **Tiempo = 15 ddi**\n\n-   **Resultados:** Los tratamientos se agrupan en dos conjuntos.\n\n    El grupo 'a' está compuesto por **As 150 mg/L Pb** (57.3) y **As 100 mg/L Pb** (63.0). Estos no difieren significativamente entre sí.\\\n    El tratamiento **As 200 mg/L Pb** (75.3) forma un grupo distinto ('b'), que es significativamente mayor que el grupo 'a'.\n\n    **Conclusión:** A los 15 días, el tratamiento de **mayor concentración (As 200 mg/L Pb) es significativamente superior** a los otros dos. Sin embargo, no se detecta una diferencia significativa entre las concentraciones de 100 y 150 mg/L de Pb.\n\n⏳ **Tiempo = 20 ddi**\n\n-   **Resultados:** Los resultados son similares a los de 15 ddi, con dos grupos.\n\n    **As 100 mg/L Pb** (86.6) forma el grupo 'a'.\\\n    **As 150 mg/L Pb** (92.9) y **As 200 mg/L Pb** (94.4) comparten el grupo 'b', lo que indica que **no son significativamente diferentes** entre sí.\\\n    El grupo 'b' (150 y 200 mg/L Pb) es significativamente diferente y mayor que el grupo 'a' (100 mg/L Pb).\n\n    **Conclusión:** Al final del período de evaluación (20 días), la **menor concentración de Pb (100 mg/L) resulta en una respuesta significativamente inferior** a las dos concentraciones más altas (150 y 200 mg/L). Las concentraciones de 150 y 200 mg/L de Pb tienen efectos estadísticamente equivalentes.\n\n### **Visualización de resultados**\n\n**Interpretación:** El análisis estadístico de la interacción entre el **Tratamiento** (diferentes concentraciones de Plomo) y el **Tiempo** revela una dinámica evolutiva del efecto medido. Si bien la tendencia general muestra un incremento en el resultado para todos los tratamientos a lo largo de los 20 días, la diferenciación estadística varía críticamente según el momento.\n\nAl inicio (0 ddi), no se registraron diferencias significativas entre las tres concentraciones. La máxima diferenciación se alcanzó a los **10 ddi**, donde el tratamiento de $200 \\text{ mg/L Pb}$ fue significativamente superior al de $150 \\text{ mg/L Pb}$, y este a su vez fue superior al de $100 \\text{ mg/L Pb}$, estableciendo una clara jerarquía.\n\nPosteriormente, a medida que el experimento progresó (15 y 20 ddi), los tratamientos de **mayor concentración convergieron estadísticamente**. A los 20 ddi, el tratamiento de $100 \\text{ mg/L Pb}$ resultó ser significativamente inferior y distinto (grupo 'a') de los tratamientos de $150 \\text{ mg/L Pb}$ y $200 \\text{ mg/L Pb}$.\n\nEn conclusión, el resultado más importante es que, si bien el tratamiento de **mayor concentración (**$200 \\text{ mg/L Pb}$) ejerce el efecto más rápido y fuerte en las etapas intermedias, al finalizar el estudio (20 ddi), la concentración de $150 \\text{ mg/L Pb}$ es estadísticamente igual de efectiva que la de $200 \\text{ mg/L Pb}$, y ambas son significativamente más efectivas que la concentración más baja.\n",
    "supporting": [
      "Chapter_06_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}