<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Capítulo 5. Diseño en Bloques Completos al Azar (DBCA) – R para Microbiología Industrial: Análisis de Datos y Diseño Experimental con un Enfoque Práctico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter_06.html" rel="next">
<link href="./Chapter_04.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-806c95bdecf85540f7beab145150c922.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter_05.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Capítulo 5. Diseño en Bloques Completos al Azar (DBCA)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R para Microbiología Industrial: Análisis de Datos y Diseño Experimental con un Enfoque Práctico</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/udesanalitica/r-para-mi" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Descargar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Descargar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./R-para-Microbiología-Industrial--Análisis-de-Datos-y-Diseño-Experimental-con-un-Enfoque-Práctico.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Descargar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./R-para-Microbiología-Industrial--Análisis-de-Datos-y-Diseño-Experimental-con-un-Enfoque-Práctico.epub">
              <i class="bi bi-journal pe-1"></i>
            Descargar ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./autores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Autores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agradecimientos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Agradecimientos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Capítulo 1. Introducción al software R y la interfaz RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Capítulo 2. Análisis bibliométrico para la gestión del diseño experimentos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Capítulo 3. Generalidades del Diseño Experimental</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Capítulo 4. Diseño Completamente al Azar (DCA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter_05.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Capítulo 5. Diseño en Bloques Completos al Azar (DBCA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Capítulo 6. Uso de Inteligencia Artificial para la simulación de datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#modelo-teórico-para-el-diseño-de-bloques-completamente-al-azar-dbca" id="toc-modelo-teórico-para-el-diseño-de-bloques-completamente-al-azar-dbca" class="nav-link active" data-scroll-target="#modelo-teórico-para-el-diseño-de-bloques-completamente-al-azar-dbca"><span class="header-section-number">8.1</span> Modelo teórico para el Diseño de Bloques Completamente al Azar (DBCA)</a></li>
  <li><a href="#análisis-de-varianza" id="toc-análisis-de-varianza" class="nav-link" data-scroll-target="#análisis-de-varianza"><span class="header-section-number">8.2</span> Análisis de varianza</a>
  <ul class="collapse">
  <li><a href="#tabla-anova-para-un-diseño-en-bloques-completos-al-azar" id="toc-tabla-anova-para-un-diseño-en-bloques-completos-al-azar" class="nav-link" data-scroll-target="#tabla-anova-para-un-diseño-en-bloques-completos-al-azar"><span class="header-section-number">8.2.1</span> Tabla ANOVA para un diseño en bloques completos al azar</a></li>
  </ul></li>
  <li><a href="#problema" id="toc-problema" class="nav-link" data-scroll-target="#problema"><span class="header-section-number">8.3</span> Problema</a></li>
  <li><a href="#estructura-de-la-base-de-datos" id="toc-estructura-de-la-base-de-datos" class="nav-link" data-scroll-target="#estructura-de-la-base-de-datos"><span class="header-section-number">8.4</span> Estructura de la base de datos</a></li>
  <li><a href="#unidad-experimental" id="toc-unidad-experimental" class="nav-link" data-scroll-target="#unidad-experimental"><span class="header-section-number">8.5</span> Unidad experimental</a></li>
  <li><a href="#definición-de-bloques" id="toc-definición-de-bloques" class="nav-link" data-scroll-target="#definición-de-bloques"><span class="header-section-number">8.6</span> Definición de bloques</a></li>
  <li><a href="#descripción-de-las-variables-del-experimento" id="toc-descripción-de-las-variables-del-experimento" class="nav-link" data-scroll-target="#descripción-de-las-variables-del-experimento"><span class="header-section-number">8.7</span> Descripción de las variables del experimento</a></li>
  <li><a href="#instalar-paquetes-solo-una-vez" id="toc-instalar-paquetes-solo-una-vez" class="nav-link" data-scroll-target="#instalar-paquetes-solo-una-vez"><span class="header-section-number">8.8</span> Instalar Paquetes (solo una vez)</a></li>
  <li><a href="#cargar-las-librerias-necesarias-para-el-análisis" id="toc-cargar-las-librerias-necesarias-para-el-análisis" class="nav-link" data-scroll-target="#cargar-las-librerias-necesarias-para-el-análisis"><span class="header-section-number">8.9</span> Cargar las librerias necesarias para el análisis</a></li>
  <li><a href="#importar-datos-desde-excel" id="toc-importar-datos-desde-excel" class="nav-link" data-scroll-target="#importar-datos-desde-excel"><span class="header-section-number">8.10</span> Importar datos desde Excel</a></li>
  <li><a href="#exploración-inicial-y-estructura-de-la-base-de-datos" id="toc-exploración-inicial-y-estructura-de-la-base-de-datos" class="nav-link" data-scroll-target="#exploración-inicial-y-estructura-de-la-base-de-datos"><span class="header-section-number">8.11</span> Exploración inicial y estructura de la base de datos</a></li>
  <li><a href="#convertir-variables-a-factores" id="toc-convertir-variables-a-factores" class="nav-link" data-scroll-target="#convertir-variables-a-factores"><span class="header-section-number">8.12</span> Convertir variables a factores</a></li>
  <li><a href="#modelo-lineal-para-dbca" id="toc-modelo-lineal-para-dbca" class="nav-link" data-scroll-target="#modelo-lineal-para-dbca"><span class="header-section-number">8.13</span> Modelo lineal para DBCA</a></li>
  <li><a href="#interpretación" id="toc-interpretación" class="nav-link" data-scroll-target="#interpretación"><span class="header-section-number">8.14</span> Interpretación</a></li>
  <li><a href="#anova-para-diseño-de-bloques-completos-al-azar--dbca-" id="toc-anova-para-diseño-de-bloques-completos-al-azar--dbca-" class="nav-link" data-scroll-target="#anova-para-diseño-de-bloques-completos-al-azar--dbca-"><span class="header-section-number">8.15</span> ANOVA para Diseño de Bloques Completos al Azar -DBCA-</a></li>
  <li><a href="#verificación-de-supuestos" id="toc-verificación-de-supuestos" class="nav-link" data-scroll-target="#verificación-de-supuestos"><span class="header-section-number">8.16</span> Verificación de supuestos</a>
  <ul class="collapse">
  <li><a href="#normalidad-de-residuos-shapiro-wilk" id="toc-normalidad-de-residuos-shapiro-wilk" class="nav-link" data-scroll-target="#normalidad-de-residuos-shapiro-wilk"><span class="header-section-number">8.16.1</span> Normalidad de residuos (Shapiro-Wilk)</a></li>
  <li><a href="#interpretación-1" id="toc-interpretación-1" class="nav-link" data-scroll-target="#interpretación-1"><span class="header-section-number">8.16.2</span> Interpretación</a></li>
  <li><a href="#homocedasticidad" id="toc-homocedasticidad" class="nav-link" data-scroll-target="#homocedasticidad"><span class="header-section-number">8.16.3</span> Homocedasticidad</a></li>
  <li><a href="#gráfico-de-residuos-vs.-valores-ajustados" id="toc-gráfico-de-residuos-vs.-valores-ajustados" class="nav-link" data-scroll-target="#gráfico-de-residuos-vs.-valores-ajustados"><span class="header-section-number">8.16.4</span> Gráfico de Residuos vs.&nbsp;Valores Ajustados</a></li>
  <li><a href="#independencia-de-residuos" id="toc-independencia-de-residuos" class="nav-link" data-scroll-target="#independencia-de-residuos"><span class="header-section-number">8.16.5</span> Independencia de residuos</a></li>
  </ul></li>
  <li><a href="#pruebas-aposteriori" id="toc-pruebas-aposteriori" class="nav-link" data-scroll-target="#pruebas-aposteriori"><span class="header-section-number">8.17</span> <strong>Pruebas aposteriori</strong></a>
  <ul class="collapse">
  <li><a href="#tukey-hsd-agrupamiento-con-letras" id="toc-tukey-hsd-agrupamiento-con-letras" class="nav-link" data-scroll-target="#tukey-hsd-agrupamiento-con-letras"><span class="header-section-number">8.17.1</span> Tukey HSD (agrupamiento con letras)</a></li>
  <li><a href="#comparaciones-múltiples-con-lsd" id="toc-comparaciones-múltiples-con-lsd" class="nav-link" data-scroll-target="#comparaciones-múltiples-con-lsd"><span class="header-section-number">8.17.2</span> Comparaciones múltiples con LSD</a></li>
  <li><a href="#visualización-de-resultados" id="toc-visualización-de-resultados" class="nav-link" data-scroll-target="#visualización-de-resultados"><span class="header-section-number">8.17.3</span> Visualización de resultados</a></li>
  <li><a href="#caja-y-bigote-boxplot-en-ggplot2" id="toc-caja-y-bigote-boxplot-en-ggplot2" class="nav-link" data-scroll-target="#caja-y-bigote-boxplot-en-ggplot2"><span class="header-section-number">8.17.4</span> Caja y Bigote (Boxplot en ggplot2)</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/udesanalitica/r-para-mi/edit/main/Chapter_05.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/udesanalitica/r-para-mi/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li><li><a href="https://github.com/udesanalitica/r-para-mi/blob/main/Chapter_05.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Capítulo 5. Diseño en Bloques Completos al Azar (DBCA)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/4_DBCA/DBCA.PNG" class="img-fluid figure-img"></p>
<figcaption>Figura 29. Mapa conceptual (p.&nbsp;85). Gutiérrez Pulido, H., y De la Vara Salazar, R. (2012). Análisis y diseño de experimentos (3ª ed.). McGraw-Hill/Interamericana de México. ISBN: 9786071507259.</figcaption>
</figure>
</div>
<p>La figura 29 presenta los principales componentes de los <strong>diseños en bloques</strong> (Figura 29), una estrategia experimental usada para controlar la variabilidad mediante la formación de grupos homogéneos llamados <em>bloques</em>. Entre estos diseños se encuentra el <strong>Diseño en Bloques Completos al Azar (DBCA)</strong>, el cual incorpora el <em>efecto de bloque</em> y requiere definir claramente las <strong>hipótesis</strong>, el <strong>modelo estadístico</strong>, así como la <strong>selección y aleatorización</strong> de las unidades experimentales. El análisis estadístico del DBCA se realiza mediante un <strong>ANOVA de dos vías</strong>, el cual permite evaluar simultáneamente el efecto de los tratamientos y de los bloques sobre la variable respuesta.</p>
<p>Otros diseños relacionados incluyen el <strong>diseño en bloques incompletos balanceados</strong> y los diseños <strong>en cuadro latino</strong> y <strong>grecolatino</strong>, los cuales permiten controlar simultáneamente múltiples fuentes de variación. Cada uno de estos diseños exige un procedimiento estructurado que abarca la formulación del modelo, el análisis de varianza correspondiente y la <strong>interpretación</strong> de los resultados.</p>
<section id="modelo-teórico-para-el-diseño-de-bloques-completamente-al-azar-dbca" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="modelo-teórico-para-el-diseño-de-bloques-completamente-al-azar-dbca"><span class="header-section-number">8.1</span> Modelo teórico para el Diseño de Bloques Completamente al Azar (DBCA)</h2>
<p>El <strong>Diseño en Bloques Completos al Azar (DBCA)</strong> se utiliza cuando existe una fuente de variación conocida <strong>denominada <em>bloques</em></strong> que puede influir en la variable de respuesta. Para controlar esa variabilidad, las unidades experimentales se agrupan en bloques homogéneos, y dentro de cada bloque los tratamientos se asignan aleatoriamente <span class="citation" data-cites="gutierrez2012analisis Montgomery2017">(<a href="references.html#ref-gutierrez2012analisis" role="doc-biblioref">Gutiérrez Pulido &amp; Vara Salazar, 2012</a>; <a href="references.html#ref-Montgomery2017" role="doc-biblioref">Montgomery, 2017</a>)</span>.</p>
<p>El modelo lineal aditivo correspondiente al DBCA se expresa como:</p>
<p><span class="math display">\[
Y_{ij} = \mu + \tau_i + \beta_j + \varepsilon_{ij}
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(Y_{ij}\)</span>: valor observado del tratamiento <span class="math inline">\(i\)</span> en el bloque <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\mu\)</span>: media general</li>
<li><span class="math inline">\(\displaystyle \tau_i\)</span>: efecto del tratamiento <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\displaystyle \beta_j\)</span>: efecto del bloque <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\displaystyle \varepsilon_{ij}\)</span>: error aleatorio asociado, con <span class="math inline">\(\displaystyle \varepsilon_{ij} \sim N(0,\sigma^2)\)</span></li>
</ul>
<p>Para ello se formulan las siguientes hipótesis estadísticas:</p>
<p><span class="math display">\[
H_0 : \mu_1 = \mu_2 = \cdots = \mu_k
\]</span></p>
<p><span class="math display">\[
H_A : \mu_i \ne \mu_j \quad \text{para algún } i \ne j
\]</span></p>
<p>Estas hipótesis permiten evaluar si existen diferencias significativas entre los tratamientos más allá de la variabilidad explicada por los bloques.</p>
</section>
<section id="análisis-de-varianza" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="análisis-de-varianza"><span class="header-section-number">8.2</span> Análisis de varianza</h2>
<p>De acuerdo con <span class="citation" data-cites="gutierrez2012analisis">(<a href="references.html#ref-gutierrez2012analisis" role="doc-biblioref">Gutiérrez Pulido &amp; Vara Salazar, 2012</a>)</span>, las hipótesis planteadas en las ecuaciones anteriores se evalúan mediante un análisis de varianza de dos vías, debido a que en el DBCA es necesario considerar simultáneamente dos fuentes de variación: los tratamientos y los bloques. La Tabla presenta el formato general del ANOVA correspondiente a un diseño en bloques completos al azar.</p>
<section id="tabla-anova-para-un-diseño-en-bloques-completos-al-azar" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="tabla-anova-para-un-diseño-en-bloques-completos-al-azar"><span class="header-section-number">8.2.1</span> Tabla ANOVA para un diseño en bloques completos al azar</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Fuente de variabilidad</th>
<th>Suma de cuadrados</th>
<th>Grados de libertad</th>
<th>Cuadrado medio</th>
<th>Estadístico F</th>
<th>Valor-p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tratamientos</td>
<td><span class="math inline">\(SC_{TRAT}\)</span></td>
<td><span class="math inline">\(k - 1\)</span></td>
<td><span class="math inline">\(CM_{TRAT}\)</span></td>
<td><span class="math inline">\(F_0 = \frac{CM_{TRAT}}{CM_E}\)</span></td>
<td><span class="math inline">\(P(F &gt; F_0)\)</span></td>
</tr>
<tr class="even">
<td>Bloques</td>
<td><span class="math inline">\(SC_B\)</span></td>
<td><span class="math inline">\(b - 1\)</span></td>
<td><span class="math inline">\(CM_B\)</span></td>
<td><span class="math inline">\(F_0 = \frac{CM_{B}}{CM_E}\)</span></td>
<td><span class="math inline">\(P(F &gt; F_0)\)</span></td>
</tr>
<tr class="odd">
<td>Error</td>
<td><span class="math inline">\(SC_E\)</span></td>
<td><span class="math inline">\((k - 1)(b - 1)\)</span></td>
<td><span class="math inline">\(CM_E\)</span></td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>Total</td>
<td><span class="math inline">\(SC_T\)</span></td>
<td><span class="math inline">\(kb - 1\)</span></td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>Nota: SC: Suma de cuadrados; CM: Cuadrado medio; <span class="math inline">\(k\)</span>: número de tratamientos; <span class="math inline">\(b\)</span>: número de bloques. TRAT: Tratamiento.</p>
</section>
</section>
<section id="problema" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="problema"><span class="header-section-number">8.3</span> Problema</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>El crecimiento de las plantas de frijol (<em>Phaseolus vulgaris</em>) depende en gran medida de la interacción entre sus raíces y los microorganismos del suelo, especialmente los rizobios, los cuales establecen una relación simbiótica mediante la formación de nódulos radiculares que facilitan la fijación biológica de nitrógeno (FBN). Este proceso constituye una fuente natural y sostenible de nitrógeno, fundamental para el desarrollo y rendimiento del cultivo.</p>
<p>No obstante, la eficiencia de esta simbiosis puede verse afectada por factores edáficos y ambientales como la composición del suelo, la disponibilidad de humedad, la temperatura y la intensidad lumínica, los cuales generan variabilidad en las condiciones experimentales y pueden influir directamente sobre el crecimiento de las plantas y la actividad microbiana asociada.</p>
<p>Debido a esta variabilidad, resulta apropiado emplear un Diseño en Bloques Completos al Azar (DBCA), donde los bloques permiten controlar parcialmente el efecto de factores ambientales no controlados. En este contexto, se evaluó la respuesta del frijol frente a diferentes tratamientos de fertilización que combinan fuentes químicas y biológicas, incluyendo bioinoculantes y abonos orgánicos, con el propósito de identificar diferencias significativas en el crecimiento del cultivo y promover estrategias de manejo más sostenibles (Figura 30)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/4_DBCA/DBCA_frijol.png" class="img-fluid figure-img" width="326"></p>
<figcaption>Figura 30.Plantas de <em>Phaseolus vulgaris</em> utilizadas en el experimento.</figcaption>
</figure>
</div>
<p>Imagen suministrada por el profesor Christian Chacín. Laboratorio de Cultivos Vegetales UDES (2025).</p>
</div>
</div>
</section>
<section id="estructura-de-la-base-de-datos" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="estructura-de-la-base-de-datos"><span class="header-section-number">8.4</span> Estructura de la base de datos</h2>
<p>El presente experimento se estructuró bajo un <strong>Diseño en Bloques Completos al Azar (DBCA)</strong> con el objetivo de evaluar el efecto de diferentes tratamientos de fertilización sobre el crecimiento de plantas de frijol (<em>Phaseolus vulgaris</em>). Este diseño permite controlar parcialmente la variabilidad asociada a factores ambientales no experimentales mediante la conformación de bloques homogéneos.</p>
<p>Se establecieron tres bloques (A, B y C), dentro de los cuales se asignaron aleatoriamente cuatro tratamientos de fertilización:</p>
<ul>
<li><p><strong>NPK comercial;</strong></p></li>
<li><p><strong>NPK + bioinoculante;</strong></p></li>
<li><p><strong>Orgánico + NPK (50:50);</strong></p></li>
<li><p><strong>Orgánico + NPK.</strong></p></li>
</ul>
<p>Cada tratamiento fue evaluado mediante diez observaciones dentro de cada bloque, generando un diseño balanceado con un total de 120 unidades experimentales.</p>
<p>La variable respuesta, denominada <code>Resultado</code>, corresponde a una variable cuantitativa continua asociada al crecimiento vegetal, expresada en valores decimales.</p>
</section>
<section id="unidad-experimental" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="unidad-experimental"><span class="header-section-number">8.5</span> Unidad experimental</h2>
<blockquote class="blockquote">
<p>Cada planta de <em>Phaseolus vulgaris</em> evaluada dentro de cada combinación tratamiento × bloque constituyó una unidad experimental independiente.</p>
</blockquote>
</section>
<section id="definición-de-bloques" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="definición-de-bloques"><span class="header-section-number">8.6</span> Definición de bloques</h2>
<blockquote class="blockquote">
<p>Los bloques correspondieron a diferentes sectores del área experimental con condiciones ambientales relativamente homogéneas, utilizados para controlar parcialmente la variabilidad asociada a factores externos como humedad, iluminación o características del suelo.</p>
</blockquote>
</section>
<section id="descripción-de-las-variables-del-experimento" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="descripción-de-las-variables-del-experimento"><span class="header-section-number">8.7</span> Descripción de las variables del experimento</h2>
<p>El diseño experimental corresponde a un Diseño en Bloques Completos al Azar (DBCA), en el cual se evaluaron diferentes tratamientos de fertilización en plantas de frijol (<em>Phaseolus vulgaris</em>). Los bloques representan grupos homogéneos de unidades experimentales, mientras que la variable respuesta cuantifica el efecto de los tratamientos sobre el crecimiento vegetal.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Tipo de variable</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Tratamiento</strong></td>
<td style="text-align: left;">Cualitativa nominal</td>
<td style="text-align: left;">Incluye los diferentes tratamientos de fertilización evaluados: NPK comercial, NPK + bioinoculante, Orgánico + NPK (50:50) y fertilización orgánica.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Bloque</strong></td>
<td style="text-align: left;">Cualitativa nominal</td>
<td style="text-align: left;">Factor de bloqueo que agrupa las unidades experimentales bajo condiciones similares. Los bloques se identifican como A, B y C.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Resultado</strong></td>
<td style="text-align: left;">Cuantitativa continua</td>
<td style="text-align: left;">Variable respuesta asociada al crecimiento de las plantas, expresada en valores decimales (por ejemplo, altura de planta en cm).</td>
</tr>
</tbody>
</table>
</section>
<section id="instalar-paquetes-solo-una-vez" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="instalar-paquetes-solo-una-vez"><span class="header-section-number">8.8</span> Instalar Paquetes (solo una vez)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("readxl")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("car") </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("agricolae") </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("lmtest") </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ggplot2")</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("gtable")</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-las-librerias-necesarias-para-el-análisis" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="cargar-las-librerias-necesarias-para-el-análisis"><span class="header-section-number">8.9</span> Cargar las librerias necesarias para el análisis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest) </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importar-datos-desde-excel" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="importar-datos-desde-excel"><span class="header-section-number">8.10</span> Importar datos desde Excel</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>DBCA <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/R-Proyectos/r-para-mi/data/DBCA_Frijol/DBCA_frijol.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>DBCA<span class="sc">$</span>Tratamiento[DBCA<span class="sc">$</span>Tratamiento <span class="sc">==</span> <span class="st">"Organico + NPK (50:50)"</span>] <span class="ot">&lt;-</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="st">"Orgánico + NPK (50:50)"</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploración-inicial-y-estructura-de-la-base-de-datos" class="level2" data-number="8.11">
<h2 data-number="8.11" class="anchored" data-anchor-id="exploración-inicial-y-estructura-de-la-base-de-datos"><span class="header-section-number">8.11</span> Exploración inicial y estructura de la base de datos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(DBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(DBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tratamiento" "Bloque"      "Resultado"  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(DBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [120 × 3] (S3: tbl_df/tbl/data.frame)
 $ Tratamiento: chr [1:120] "NPK Comercial" "NPK Comercial" "NPK Comercial" "NPK Comercial" ...
 $ Bloque     : chr [1:120] "A" "A" "A" "A" ...
 $ Resultado  : num [1:120] 51.5 49.6 51.9 54.6 49.3 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DBCA<span class="sc">$</span>Resultado)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  44.71   52.30   56.76   57.26   61.24   72.39 </code></pre>
</div>
</div>
</section>
<section id="convertir-variables-a-factores" class="level2" data-number="8.12">
<h2 data-number="8.12" class="anchored" data-anchor-id="convertir-variables-a-factores"><span class="header-section-number">8.12</span> Convertir variables a factores</h2>
<p>Para garantizar un análisis adecuado bajo un <strong>Diseño en Bloques Completos al Azar (DBCA)</strong>, las variables <code>Tratamiento</code> y <code>Bloque</code> deben definirse como factores en R. Esta conversión permite que el modelo estadístico reconozca ambas variables como factores categóricos asociados a los efectos experimentales del estudio, evitando que sean interpretadas como variables numéricas continuas.</p>
<p>La variable <code>Resultado</code>, por su parte, se mantiene como una variable cuantitativa continua.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>DBCA<span class="sc">$</span>Tratamiento <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(DBCA<span class="sc">$</span>Tratamiento)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>DBCA<span class="sc">$</span>Bloque      <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(DBCA<span class="sc">$</span>Bloque)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>DBCA<span class="sc">$</span>Resultado   <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DBCA<span class="sc">$</span>Resultado)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modelo-lineal-para-dbca" class="level2" data-number="8.13">
<h2 data-number="8.13" class="anchored" data-anchor-id="modelo-lineal-para-dbca"><span class="header-section-number">8.13</span> Modelo lineal para DBCA</h2>
<p>Con el fin de evaluar simultáneamente el efecto de los tratamientos de fertilización y de los bloques experimentales sobre la variable respuesta, se ajustó un modelo lineal correspondiente al Diseño en Bloques Completos al Azar (DBCA). Este modelo incorpora tanto el efecto de los tratamientos como la variabilidad asociada a los bloques, permitiendo controlar parcialmente las diferencias ambientales presentes en el experimento.</p>
<p>El modelo se ajustó en R mediante el siguiente código:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>modeloDBCA <span class="ot">&lt;-</span> <span class="fu">aov</span>(Resultado <span class="sc">~</span> Tratamiento <span class="sc">+</span> Bloque,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> DBCA)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeloDBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
Tratamiento   3   3602  1200.6 153.749 &lt;2e-16 ***
Bloque        2     11     5.4   0.688  0.505    
Residuals   114    890     7.8                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="interpretación" class="level2" data-number="8.14">
<h2 data-number="8.14" class="anchored" data-anchor-id="interpretación"><span class="header-section-number">8.14</span> Interpretación</h2>
<p>El análisis del modelo lineal evidenció que el factor <code>Tratamiento</code> presentó un efecto altamente significativo sobre la variable respuesta (<span class="math inline">\(F = 153.749\)</span>; <span class="math inline">\(p &lt; 2 \times 10^{-16}\)</span>), indicando que existen diferencias estadísticas entre las medias de los tratamientos evaluados.</p>
<p>Por otro lado, el factor <code>Bloque</code> no mostró un efecto significativo (<span class="math inline">\(F = 0.688\)</span>; <span class="math inline">\(p = 0.505\)</span>), lo que sugiere que la variabilidad entre bloques fue baja y no contribuyó significativamente a explicar la variación observada en el experimento.</p>
<p>En conjunto, los resultados indican que las diferencias detectadas en la altura de las plantas se deben principalmente al efecto de los tratamientos de fertilización y no a variaciones asociadas a los bloques experimentales.</p>
</section>
<section id="anova-para-diseño-de-bloques-completos-al-azar--dbca-" class="level2" data-number="8.15">
<h2 data-number="8.15" class="anchored" data-anchor-id="anova-para-diseño-de-bloques-completos-al-azar--dbca-"><span class="header-section-number">8.15</span> ANOVA para Diseño de Bloques Completos al Azar -DBCA-</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>modeloDBCA <span class="ot">&lt;-</span> <span class="fu">aov</span>(Resultado <span class="sc">~</span> Tratamiento <span class="sc">+</span> Bloque, <span class="at">data =</span> DBCA)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeloDBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
Tratamiento   3   3602  1200.6 153.749 &lt;2e-16 ***
Bloque        2     11     5.4   0.688  0.505    
Residuals   114    890     7.8                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> Los resultados del análisis de varianza (ANOVA) correspondientes al Diseño en Bloques Completos al Azar (DBCA) evidenciaron un efecto altamente significativo del factor <code>Tratamiento</code> sobre la variable respuesta <code>Resultado</code>, mientras que el factor <code>Bloque</code> no presentó un efecto estadísticamente significativo.</p>
<p>1. <strong>Efecto del Tratamiento</strong>.</p>
<p>El análisis indica que el factor Tratamiento es altamente significativo sobre la variable de Resultado. Dado que el valor <span class="math inline">\(\text{p}\)</span> es extremadamente pequeño (denotado por ‘***’), se <strong>rechaza la hipótesis nula</strong> de que no hay diferencias entre las medias de los tratamientos. Esto significa que existe una <strong>diferencia estadísticamente significativa</strong> en el Resultado al menos entre dos de los niveles de Tratamiento. <strong>Grados de Libertad (Df):</strong> 3. <strong>Valor F (F value):</strong> 153.749. <strong>Valor p (</strong><span class="math inline">\(\text{Pr}(&gt;F)\)</span>): <span class="math inline">\(&lt;2 \text{e}-16\)</span> (Menor que <span class="math inline">\(0.001\)</span>)</p>
<p>El factor <code>Tratamiento</code> mostró diferencias altamente significativas entre sus media (<span class="math inline">\(F=153.749\)</span>, <span class="math inline">\(p &lt; 2 \times 10^{-16}\)</span>. En consecuencia, se rechaza la hipótesis nula de igualdad de medias entre tratamientos, indicando que al menos uno de los tratamientos de fertilización produjo un efecto diferente sobre el crecimiento de las plantas de frijol.</p>
<p>Estos resultados sugieren que el tipo de fertilización influye significativamente sobre la variable respuesta evaluada.</p>
<ul>
<li><p>Grados de libertad: <span class="math inline">\(Df=3\)</span></p></li>
<li><p>Cuadrado medio: <span class="math inline">\(CM_{TRAT} = 1200.6\)</span></p></li>
<li><p>Estadístico F: <span class="math inline">\(F = 153.749\)</span></p></li>
<li><p>Valor de p: <span class="math inline">\(p &lt; 2 \times 10^{-16}\)</span></p></li>
</ul>
<p>2. <strong>Efecto del Bloque.</strong></p>
<p>El factor <code>Bloque</code> no presentó diferencias estadísticamente significativas (<span class="math inline">\(F = 0.688\)</span>; <span class="math inline">\(p = 0.505\)</span>). Esto indica que la variabilidad asociada a los bloques no fue suficientemente grande para afectar significativamente la variable respuesta.</p>
<p>Aunque el bloqueo fue incorporado para controlar posibles fuentes de variación ambiental, los resultados sugieren que las condiciones entre bloques fueron relativamente homogéneas o que el efecto de los tratamientos fue considerablemente mayor que la variabilidad atribuida al bloqueo.</p>
<ul>
<li>Grados de libertad: <span class="math inline">\(Df = 2\)</span></li>
</ul>
<!-- -->
<ul>
<li>Cuadrado medio: <span class="math inline">\(CM_B = 5.4\)</span></li>
</ul>
<!-- -->
<ul>
<li>Estadístico F: <span class="math inline">\(F = 0.688\)</span></li>
</ul>
<!-- -->
<ul>
<li>Valor de p: <span class="math inline">\(p = 0.505\)</span></li>
</ul>
<p>3. <strong>Resumen del Modelo.</strong></p>
<p>El análisis evidenció que el factor <code>Tratamiento</code> ejerce una influencia significativa sobre la variable respuesta, mientras que el factor <code>Bloque</code> no contribuyó significativamente a explicar la variabilidad observada en los datos.</p>
<p>Dado que el efecto de tratamientos resultó significativo, es necesario realizar pruebas de comparaciones múltiples <em>a posteriori</em> (por ejemplo, Tukey, LSD o Scheffé) con el fin de identificar específicamente cuáles tratamientos difieren entre sí.</p>
</section>
<section id="verificación-de-supuestos" class="level2" data-number="8.16">
<h2 data-number="8.16" class="anchored" data-anchor-id="verificación-de-supuestos"><span class="header-section-number">8.16</span> Verificación de supuestos</h2>
<p>Para garantizar la validez de los resultados del análisis de varianza (ANOVA), es necesario verificar el cumplimiento de los supuestos estadísticos asociados al modelo. El incumplimiento de estos supuestos puede afectar la confiabilidad de las inferencias obtenidas.</p>
<p>Los principales supuestos evaluados fueron:</p>
<ul>
<li><p><strong>Normalidad de los residuos:</strong> establece que los residuos del modelo deben aproximarse a una distribución normal. Este supuesto se evaluó mediante la prueba de Shapiro-Wilk y gráficos diagnósticos.</p></li>
<li><p><strong>Homogeneidad de varianzas (homocedasticidad):</strong> supone que la variabilidad de la variable respuesta es similar entre los tratamientos y bloques evaluados.</p></li>
<li><p><strong>Independencia de las observaciones:</strong> implica que los errores experimentales sean independientes entre sí, sin autocorrelación entre las observaciones.</p></li>
</ul>
<section id="normalidad-de-residuos-shapiro-wilk" class="level3" data-number="8.16.1">
<h3 data-number="8.16.1" class="anchored" data-anchor-id="normalidad-de-residuos-shapiro-wilk"><span class="header-section-number">8.16.1</span> Normalidad de residuos (Shapiro-Wilk)</h3>
<p>La normalidad de los residuos del modelo se evaluó mediante la prueba de Shapiro-Wilk, la cual contrasta la hipótesis nula de que los residuos provienen de una distribución normal. Valores de <span class="math inline">\(p = 0.505\)</span> indican que no existen evidencias suficientes para rechazar dicho supuesto.</p>
<p>El análisis se realizó mediante el siguiente script en R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modeloDBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(res)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  res
W = 0.99559, p-value = 0.9725</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> La prueba de Shapiro-Wilk aplicada a los residuos del modelo arrojó un estadístico <span class="math inline">\(W = 0.995\)</span> y un valor de <span class="math inline">\(p = 0.9725\)</span>, superior al nivel de significancia de 0.05. Por lo tanto, no existen evidencias estadísticas para rechazar la hipótesis nula de normalidad, indicando que los residuos del modelo presentan una distribución aproximadamente normal. En consecuencia, se considera cumplido el supuesto de normalidad requerido para el análisis de varianza (ANOVA).</p>
<p><strong>Gráfico Q-Q de los residuos estandarizados</strong></p>
<p>Como complemento a la prueba de Shapiro-Wilk, se elaboró un gráfico Q-Q (<em>Quantile-Quantile</em>) de los residuos estandarizados del modelo. Este gráfico permite evaluar visualmente el supuesto de normalidad mediante la comparación entre los cuantiles observados de los residuos y los cuantiles teóricos de una distribución normal.</p>
<p>Cuando los puntos se distribuyen aproximadamente sobre la línea diagonal de referencia, se considera que los residuos presentan un comportamiento compatible con la normalidad.</p>
<p>El análisis se realizó mediante el siguiente script en R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(res)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(res, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_05_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(res, <span class="at">main =</span> <span class="st">"Histograma de residuos"</span>, <span class="at">xlab =</span> <span class="st">"Residuos"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_05_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretación-1" class="level3" data-number="8.16.2">
<h3 data-number="8.16.2" class="anchored" data-anchor-id="interpretación-1"><span class="header-section-number">8.16.2</span> Interpretación</h3>
<p>El gráfico Q-Q mostró que los residuos estandarizados se distribuyen cercanos a la línea diagonal de referencia, sin evidenciar desviaciones importantes o patrones sistemáticos. Esto sugiere que los residuos presentan una distribución aproximadamente normal, respaldando visualmente el cumplimiento del supuesto de normalidad requerido para el análisis de varianza (ANOVA).</p>
</section>
<section id="homocedasticidad" class="level3" data-number="8.16.3">
<h3 data-number="8.16.3" class="anchored" data-anchor-id="homocedasticidad"><span class="header-section-number">8.16.3</span> Homocedasticidad</h3>
<p>La homogeneidad de varianzas entre tratamientos constituye uno de los supuestos fundamentales del análisis de varianza (ANOVA). Para evaluar este supuesto se aplicaron las pruebas de Bartlett, Levene y Fligner-Killeen, las cuales permiten determinar si la variabilidad de la variable respuesta es similar entre los grupos evaluados.</p>
<p>El análisis se realizó mediante el siguiente script en R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(Resultado <span class="sc">~</span> Tratamiento, <span class="at">data =</span> DBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  Resultado by Tratamiento
Bartlett's K-squared = 7.4355, df = 3, p-value = 0.05924</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(Resultado <span class="sc">~</span> Tratamiento, <span class="at">data =</span> DBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)
group   3  1.3691 0.2557
      116               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fligner.test</span>(Resultado <span class="sc">~</span> Tratamiento, <span class="at">data =</span> DBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fligner-Killeen test of homogeneity of variances

data:  Resultado by Tratamiento
Fligner-Killeen:med chi-squared = 3.3125, df = 3, p-value = 0.3459</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong></p>
<p>Las pruebas de Bartlett, Levene y Fligner-Killeen presentaron valores de ppp superiores al nivel de significancia de 0.05, indicando que no existen evidencias estadísticas suficientes para rechazar la hipótesis nula de igualdad de varianzas entre tratamientos.</p>
<p>Aunque el valor obtenido en la prueba de Bartlett (<span class="math inline">\(p = 0.059\)</span>) se encuentra cercano al umbral de significancia, los resultados en conjunto sugieren que el supuesto de homocedasticidad se cumple razonablemente para el modelo analizado, permitiendo continuar con la interpretación del ANOVA y las pruebas de comparación múltiple.</p>
</section>
<section id="gráfico-de-residuos-vs.-valores-ajustados" class="level3" data-number="8.16.4">
<h3 data-number="8.16.4" class="anchored" data-anchor-id="gráfico-de-residuos-vs.-valores-ajustados"><span class="header-section-number">8.16.4</span> Gráfico de Residuos vs.&nbsp;Valores Ajustados</h3>
<p>Como complemento a las pruebas formales de homogeneidad de varianzas, se construyó un gráfico de residuos estandarizados frente a los valores ajustados del modelo. Este gráfico permite evaluar visualmente la presencia de patrones sistemáticos, cambios en la dispersión o posibles problemas de heterocedasticidad.</p>
<p>Cuando los residuos se distribuyen aleatoriamente alrededor de la línea horizontal en cero, sin formar estructuras definidas o patrones tipo cono, se considera que el supuesto de homogeneidad de varianzas se cumple adecuadamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Extraer valores ajustados y residuos del modelo DBCA</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>datos_homocedasticidad <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valores_Ajustados =</span> <span class="fu">fitted</span>(modeloDBCA),     <span class="co"># valores predichos del modelo</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Residuos_Std =</span> <span class="fu">rstandard</span>(modeloDBCA)        <span class="co"># residuos estandarizados</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Gráfico de residuos vs valores ajustados</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos_homocedasticidad, <span class="fu">aes</span>(<span class="at">x =</span> Valores_Ajustados, <span class="at">y =</span> Residuos_Std)) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Gráfico de Residuos vs. Valores Ajustados (Homogeneidad de Varianzas)"</span>,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Valores ajustados (predichos)"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Residuos estandarizados"</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_05_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpretación:</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Los puntos deben dispersarse aleatoriamente alrededor de y = 0</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># sin formar patrones o conos, indicando homogeneidad de varianzas.</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretación:</strong></p>
<p>Las pruebas de Bartlett, Levene y Fligner-Killeen, junto con el análisis gráfico de residuos, evidenciaron que el modelo cumple razonablemente el supuesto de homogeneidad de varianzas. El gráfico mostró una dispersión aleatoria de los residuos alrededor de la línea horizontal en cero, sin patrones sistemáticos ni cambios importantes en la variabilidad.</p>
<p>En consecuencia, se considera válido el uso del análisis de varianza (ANOVA) bajo el Diseño en Bloques Completos al Azar (DBCA), dado que no se detectaron violaciones importantes del supuesto de homocedasticidad.</p>
</section>
<section id="independencia-de-residuos" class="level3" data-number="8.16.5">
<h3 data-number="8.16.5" class="anchored" data-anchor-id="independencia-de-residuos"><span class="header-section-number">8.16.5</span> Independencia de residuos</h3>
<p>La independencia de los residuos constituye otro de los supuestos fundamentales del análisis de varianza (ANOVA). Este supuesto establece que los errores experimentales deben ser independientes entre sí, es decir, que el valor de un residuo no debe influir sobre otro.</p>
<p>Para evaluar este supuesto se aplicó la prueba de Durbin-Watson, la cual permite detectar la presencia de autocorrelación entre los residuos del modelo.</p>
<p>Las hipótesis evaluadas fueron:</p>
<ul>
<li><p><strong>Hipótesis nula (H₀):</strong> los residuos son independientes;</p></li>
<li><p><strong>Hipótesis alternativa (H₁):</strong> los residuos presentan autocorrelación.</p></li>
</ul>
<p>Valores de <strong>p-value &gt; 0.05</strong>, indican que no existen evidencias suficientes para rechazar la hipótesis nula de independencia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dwtest</span>(modeloDBCA)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  modeloDBCA
DW = 2.042, p-value = 0.4159
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong></p>
<p>La prueba de Durbin-Watson arrojó un valor de <span class="math inline">\(DW = 2.042\)</span> y un valor de <span class="math inline">\(p = 0.4159\)</span>, superior al nivel de significancia de 0.05. En consecuencia, no existen evidencias estadísticas suficientes para rechazar la hipótesis nula de independencia de los residuos.</p>
<p>Adicionalmente, la cercanía del estadístico <span class="math inline">\(DW\)</span> al valor teórico de 2.042 respalda la ausencia de autocorrelación entre los errores experimentales. Por lo tanto, se considera cumplido el supuesto de independencia requerido para la validez del análisis de varianza bajo el Diseño en Bloques Completos al Azar (DBCA).</p>
</section>
</section>
<section id="pruebas-aposteriori" class="level2" data-number="8.17">
<h2 data-number="8.17" class="anchored" data-anchor-id="pruebas-aposteriori"><span class="header-section-number">8.17</span> <strong>Pruebas aposteriori</strong></h2>
<p>Una vez verificados los supuestos de normalidad, homogeneidad de varianzas e independencia de los residuos, se realizaron pruebas de comparaciones múltiples <em>a posteriori</em> con el propósito de identificar cuáles tratamientos presentan diferencias estadísticamente significativas sobre la variable respuesta evaluada.</p>
<p>En el contexto del Diseño en Bloques Completos al Azar (DBCA), estas pruebas permiten comparar las medias ajustadas de los tratamientos considerando el efecto de bloqueo incorporado en el modelo experimental. Entre las pruebas más utilizadas se encuentran Tukey, LSD y Scheffé, las cuales permiten identificar diferencias específicas entre pares de tratamientos.</p>
<p>El uso del DBCA contribuye a reducir la variabilidad experimental asociada a factores externos mediante la conformación de bloques homogéneos, incrementando así la precisión y confiabilidad de las comparaciones estadísticas. En consecuencia, las diferencias detectadas entre tratamientos reflejan principalmente los efectos reales de las condiciones de fertilización evaluadas y no variaciones atribuibles al azar o a fuentes de variación no controladas.</p>
<section id="tukey-hsd-agrupamiento-con-letras" class="level3" data-number="8.17.1">
<h3 data-number="8.17.1" class="anchored" data-anchor-id="tukey-hsd-agrupamiento-con-letras"><span class="header-section-number">8.17.1</span> Tukey HSD (agrupamiento con letras)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">HSD.test</span>(modeloDBCA, <span class="st">"Tratamiento"</span>, <span class="at">group =</span> <span class="cn">TRUE</span>, <span class="at">console =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: modeloDBCA ~ "Tratamiento"

HSD Test for Resultado 

Mean Square Error:  7.808829 

Tratamiento,  means

                       Resultado      std  r        se   Min   Max     Q25
NPK + Bioinoculante     54.25933 2.395591 30 0.5101904 49.26 58.09 52.9100
NPK Comercial           50.29667 2.453096 30 0.5101904 44.71 54.74 48.5975
Orgánico + NPK          64.78000 3.621806 30 0.5101904 57.14 72.39 62.1700
Orgánico + NPK (50:50)  59.71300 2.488591 30 0.5101904 55.73 65.66 58.2425
                          Q50     Q75
NPK + Bioinoculante    54.045 55.9275
NPK Comercial          50.080 51.8625
Orgánico + NPK         65.070 66.9650
Orgánico + NPK (50:50) 59.480 61.0025

Alpha: 0.05 ; DF Error: 114 
Critical Value of Studentized Range: 3.687325 

Minimun Significant Difference: 1.881238 

Treatments with the same letter are not significantly different.

                       Resultado groups
Orgánico + NPK          64.78000      a
Orgánico + NPK (50:50)  59.71300      b
NPK + Bioinoculante     54.25933      c
NPK Comercial           50.29667      d</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong></p>
<p>La prueba de Tukey HSD aplicada al Diseño en Bloques Completos al Azar (DBCA) evidenció diferencias estadísticamente significativas entre todos los tratamientos evaluados sobre la altura de las plantas de frijol. El Tratamiento 4 presentó la mayor media (64.78 cm; grupo a), seguido del Tratamiento 3 (59.71 cm; grupo b), el Tratamiento 2 (54.26 cm; grupo c) y el Tratamiento 1 (50.29 cm; grupo d), el cual registró la menor media.</p>
<p>La diferencia mínima significativa obtenida mediante la prueba de Tukey fue de 1.88, superior a la observada en la prueba LSD (1.43), lo que refleja el carácter más conservador del método Tukey para el control del error por comparaciones múltiples. A pesar de ello, los tratamientos mantuvieron una separación completa, sin letras compartidas entre grupos, indicando que todas las medias difieren significativamente entre sí al nivel de confianza del 95 %.</p>
<p>Estos resultados confirman que los tratamientos ejercieron efectos claramente diferenciados sobre la altura de las plantas y respaldan la consistencia y confiabilidad de los resultados obtenidos en el experimento.</p>
</section>
<section id="comparaciones-múltiples-con-lsd" class="level3" data-number="8.17.2">
<h3 data-number="8.17.2" class="anchored" data-anchor-id="comparaciones-múltiples-con-lsd"><span class="header-section-number">8.17.2</span> Comparaciones múltiples con LSD</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>out_LSD <span class="ot">&lt;-</span> <span class="fu">LSD.test</span>(modeloDBCA, <span class="st">"Tratamiento"</span>, <span class="at">group =</span> <span class="cn">TRUE</span>, <span class="at">console =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: modeloDBCA ~ "Tratamiento"

LSD t Test for Resultado 

Mean Square Error:  7.808829 

Tratamiento,  means and individual ( 95 %) CI

                       Resultado      std  r        se      LCL      UCL   Min
NPK + Bioinoculante     54.25933 2.395591 30 0.5101904 53.24865 55.27002 49.26
NPK Comercial           50.29667 2.453096 30 0.5101904 49.28598 51.30735 44.71
Orgánico + NPK          64.78000 3.621806 30 0.5101904 63.76932 65.79068 57.14
Orgánico + NPK (50:50)  59.71300 2.488591 30 0.5101904 58.70232 60.72368 55.73
                         Max     Q25    Q50     Q75
NPK + Bioinoculante    58.09 52.9100 54.045 55.9275
NPK Comercial          54.74 48.5975 50.080 51.8625
Orgánico + NPK         72.39 62.1700 65.070 66.9650
Orgánico + NPK (50:50) 65.66 58.2425 59.480 61.0025

Alpha: 0.05 ; DF Error: 114
Critical Value of t: 1.980992 

least Significant Difference: 1.429322 

Treatments with the same letter are not significantly different.

                       Resultado groups
Orgánico + NPK          64.78000      a
Orgánico + NPK (50:50)  59.71300      b
NPK + Bioinoculante     54.25933      c
NPK Comercial           50.29667      d</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong></p>
<p>La prueba LSD (<em>Least Significant Difference</em>) aplicada al Diseño en Bloques Completos al Azar (DBCA) evidenció diferencias estadísticamente significativas entre las medias de altura de las plantas de frijol para todos los tratamientos evaluados. El Tratamiento 4 presentó la mayor altura promedio (64.78 cm; grupo a), seguido del Tratamiento 3 (59.71 cm; grupo b), el Tratamiento 2 (54.26 cm; grupo c) y finalmente el Tratamiento 1 (50.29 cm; grupo d), el cual registró la menor media.</p>
<p>La diferencia mínima significativa obtenida mediante la prueba LSD fue de 1.43, indicando que diferencias superiores a este valor se consideran estadísticamente significativas al nivel de confianza del 95 %. La ausencia de letras compartidas entre tratamientos confirma que todas las medias difieren significativamente entre sí.</p>
<p>Estos resultados indican que los tratamientos ejercieron efectos diferenciados sobre la altura de las plantas de frijol, más allá de la variabilidad experimental controlada mediante los bloques del diseño.</p>
</section>
<section id="visualización-de-resultados" class="level3" data-number="8.17.3">
<h3 data-number="8.17.3" class="anchored" data-anchor-id="visualización-de-resultados"><span class="header-section-number">8.17.3</span> Visualización de resultados</h3>
</section>
<section id="caja-y-bigote-boxplot-en-ggplot2" class="level3" data-number="8.17.4">
<h3 data-number="8.17.4" class="anchored" data-anchor-id="caja-y-bigote-boxplot-en-ggplot2"><span class="header-section-number">8.17.4</span> Caja y Bigote (Boxplot en ggplot2)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(DBCA, <span class="fu">aes</span>(<span class="at">x =</span> Tratamiento, <span class="at">y =</span> Resultado, <span class="at">fill =</span> Tratamiento)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">labs</span>( <span class="at">title =</span> <span class="st">"Distribución del resultado por tratamiento"</span>, <span class="at">x =</span> <span class="st">"Tratamiento"</span>, <span class="at">y =</span> <span class="st">"Resultado"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter_05_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretación:</strong></p>
<p>La gráfica de cajas y bigotes muestra la distribución de las alturas de las plantas de <em>Phaseolus vulgaris</em> bajo los diferentes tratamientos de fertilización evaluados mediante un Diseño en Bloques Completos al Azar (DBCA). Se observa una tendencia creciente en las medianas de los tratamientos, evidenciando un efecto progresivamente favorable sobre el crecimiento vegetal desde NPK Comercial hasta Orgánico + NPK.</p>
<p>El tratamiento Orgánico + NPK presentó las mayores alturas promedio, seguido de Orgánico + NPK (50:50), NPK + Bioinoculante y finalmente NPK Comercial, el cual registró los valores más bajos. La dispersión de los datos dentro de cada tratamiento fue relativamente homogénea, aunque se identificó un valor atípico en el tratamiento Orgánico + NPK (50:50), comportamiento frecuente en experimentos biológicos debido a la variabilidad natural entre individuos.</p>
<p>Estos resultados son consistentes con las pruebas de comparación múltiple (LSD y Tukey), las cuales evidenciaron diferencias estadísticamente significativas entre todos los tratamientos evaluados.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-gutierrez2012analisis" class="csl-entry" role="listitem">
Gutiérrez Pulido, H., &amp; Vara Salazar, R. de la. (2012). <em>An<span>á</span>lisis y dise<span>ñ</span>o de experimentos</em> (3.ª ed.). McGraw-Hill/Interamericana Editores, S.A. de C.V.
</div>
<div id="ref-Montgomery2017" class="csl-entry" role="listitem">
Montgomery, D. C. (2017). <em>Design and Analysis of Experiments</em> (9th ed.). John Wiley &amp; Sons.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/udesanalitica\.github\.io\/r-para-mi\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter_04.html" class="pagination-link" aria-label="Capítulo 4. Diseño Completamente al Azar (DCA)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Capítulo 4. Diseño Completamente al Azar (DCA)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter_06.html" class="pagination-link" aria-label="Capítulo 6. Uso de Inteligencia Artificial para la simulación de datos">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Capítulo 6. Uso de Inteligencia Artificial para la simulación de datos</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 Autores</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/udesanalitica/r-para-mi/edit/main/Chapter_05.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/udesanalitica/r-para-mi/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li><li><a href="https://github.com/udesanalitica/r-para-mi/blob/main/Chapter_05.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Publicado con Quarto y GitHub Pages</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>